### ISSUE TITLE
"overlay" is an array.

### ISSUE THREAD

**Issue by senger1985** [iobroker-community-adapters/ioBroker.tado#1]
Please process in own data points

**Comment by DutchmanNL** [comment]
in my lab this variable is NULL, can you send me the string ?
(I activated storage in plain text for this value in version 0.0.6)

<img width="1505" alt="Schermafbeelding 2019-10-12 om 03 48 24" src="https://user-images.githubusercontent.com/7318445/66692893-28369180-eca3-11e9-852e-f14c5f76edfe.png">

**Comment by senger1985** [comment]
{"type":"MANUAL","setting":{"type":"HEATING","power":"ON","temperature":{"celsius":20,"fahrenheit":68}},"termination":{"type":"MANUAL","typeSkillBasedApp":"MANUAL","projectedExpiry":null}}

**Comment by DutchmanNL** [comment]
thank you, please try version 0.0.7 : 
https://github.com/iobroker-community-adapters/ioBroker.tado/commit/2392b3a6d3c7390f7dcb7fe6b8299884e9334362

**Comment by senger1985** [comment]
![tado](https://user-images.githubusercontent.com/35745035/66700848-e1be5280-ecf5-11e9-8309-56540af47d9d.PNG)
Don't know what "termination" is.
The data point is blank

**Comment by DutchmanNL** [comment]
please try new update from GitHub 0.0.8 RC_2
