### ISSUE TITLE
Split "openWindow"

### ISSUE THREAD

**Issue by senger1985** [iobroker-community-adapters/ioBroker.tado#10]
{"detectTime": "2019-12-02T21: 28: 20Z", "durationInSeconds": 3600, "expiry": "2019-12-02T22: 28: 20Z", "residualTimeInSeconds": 3587}
And only state "residualTimeInSeconds" may be updated every few seconds.

**Comment by DutchmanNL** [comment]
Should be fixed, please try version from git 

https://github.com/iobroker-community-adapters/ioBroker.tado/commit/b096efa94037b024486e46283f5753c03c030b81#diff-7a9076d6d94e62c13d641aa71f19ae8eR1081-R1086
