### ISSUE TITLE
Update wird nicht angezeigt

### ISSUE THREAD

**Issue by maximal1981** [iobroker-community-adapters/ioBroker.tado#102]
Update wird nicht im ioBroker angezeigt und ist somit nicht möglich.
Im Änderungsprotokoll sieht man aber die v0.2.2

![Unbenannt](https://user-images.githubusercontent.com/69747314/98249830-01668f80-1f77-11eb-9b9a-b4af1c47c280.PNG)
![Unbenannt2](https://user-images.githubusercontent.com/69747314/98249836-0297bc80-1f77-11eb-8af0-238348d13b77.PNG)

**Comment by HGlab01** [comment]
You have to install it like you did for 0.2.1 by using ![image](https://user-images.githubusercontent.com/54232526/98250636-f9f3b600-1f77-11eb-804d-133ce2706b22.png)

**Comment by DutchmanNL** [comment]
> You have to install it like you did for 0.2.1 by using ![image](https://user-images.githubusercontent.com/54232526/98250636-f9f3b600-1f77-11eb-804d-133ce2706b22.png)

uh no, there is an issue with the repo load 0.2.2 is on NPM and should be visible in admin I will check with the team.

![Schermafbeelding 2020-11-05 om 15 07 47](https://user-images.githubusercontent.com/7318445/98251173-acc41400-1f78-11eb-909c-a5c0f6804ce5.png)

**Comment by DutchmanNL** [comment]
Tado ist durch einen Fehler in der latest json nicht mehr in der liste von beta Adaptern, wir dran gearbeitet diese change hier in der repo ist die Ursache.

https://github.com/ioBroker/ioBroker.repositories/commit/ab490e67f19d69575a842b4baf3ef36b7ed2ca0f#diff-1384831e45cb5b5fc71b065c642c35169d0ee196221e07b4b81075a0d3b0aed8L1450-L1453

**Comment by maximal1981** [comment]
was kann ich jetzt machen?
bzw. gibt es einen Befehl auf der CLI um das zu fixen, oder soll ich eine Datei editieren?

**Comment by DutchmanNL** [comment]
> was kann ich jetzt machen?
> bzw. gibt es einen Befehl auf der CLI um das zu fixen, oder soll ich eine Datei editieren?

yes, auf der cli : 

```
iobroker install tado@latest
```

**Comment by maximal1981** [comment]
iobroker install tado@latest
adapter "tado" already installed. Use "upgrade" to upgrade to a newer version.
iobroker upgrade tado@latest
Adapter "tado" is not in the repository and cannot be updated.

**Comment by DutchmanNL** [comment]
> iobroker install tado@latest
> adapter "tado" already installed. Use "upgrade" to upgrade to a newer version.
> iobroker upgrade tado@latest
> Adapter "tado" is not in the repository and cannot be updated.

sorry forgot this is only possible when in iobroker repo, please use : 

```
cd /opt/iobroker
npm install iobroker.tado@latest
```

**Comment by maximal1981** [comment]
ok, I have v0.2.2 installed
But the available version is still empty

![Unbenannt2](https://user-images.githubusercontent.com/69747314/98263149-c2d8d100-1f86-11eb-8cda-2d245a922bdb.PNG)

**Comment by DutchmanNL** [comment]
We (ioBroker team) See working on a fix will keep the issue open until the dependency is solved

**Comment by DutchmanNL** [comment]
Solved

![Schermafbeelding 2020-11-06 om 10 02 09](https://user-images.githubusercontent.com/7318445/98347068-332f3300-2017-11eb-8bb8-94cd68e9202e.png)

**Comment by maximal1981** [comment]
Not for me

![Unbenannt](https://user-images.githubusercontent.com/69747314/99850504-c622ae00-2b7d-11eb-9dbe-b88642825104.PNG)

**Comment by DutchmanNL** [comment]
> Not for me
> 
> ![Unbenannt](https://user-images.githubusercontent.com/69747314/99850504-c622ae00-2b7d-11eb-9dbe-b88642825104.PNG)

Is your repository set to latest (beta) of default (stable) ?

**Comment by maximal1981** [comment]
default (stable)

**Comment by DutchmanNL** [comment]
> default (stable)

Adapter is not released as stable yet, only install able as beta

**Comment by maximal1981** [comment]
ok, thanks
