### ISSUE TITLE
Unhandable information found 

### ISSUE THREAD

**Issue by Trrw** [iobroker-community-adapters/ioBroker.tado#103]
Hallo, 

ich bekomme diesen Fehler ständig im Log Angezeigt:
(27572) Send this info to developer !!! { Unhandable information found in DoHome : "autoAssistFreeTrialEnabled" with value : false

<img width="1178" alt="Bildschirmfoto 2020-11-06 um 08 34 54" src="https://user-images.githubusercontent.com/24519230/98338804-0aa13c00-200b-11eb-8d3c-cc7c2558dabc.png">

Vielen Dank
Gruß

**Comment by HGlab01** [comment]
check #95. Solved in v0.2,2, but there is an issue to install the newest version (#102)

**Comment by DutchmanNL** [comment]
Solved

![Schermafbeelding 2020-11-06 om 10 02 09](https://user-images.githubusercontent.com/7318445/98347068-332f3300-2017-11eb-8bb8-94cd68e9202e.png)
