### ISSUE TITLE
 Unhandable information found in DoHome : "autoAssistFreeTrialEnabled" with value : true

### ISSUE THREAD

**Issue by Solilord** [iobroker-community-adapters/ioBroker.tado#104]
Hi,

Seit kurzem hab ich alle paar sekunden diesen fehler im log:
(31785) Send this info to developer !!! { Unhandable information found in DoHome : "autoAssistFreeTrialEnabled" with value : true

ich habe eigentlich nicht viel geändert. Nur seit 2-3 Wochen habe ich den AutoAssist wieder abboniert

**Comment by HGlab01** [comment]
double entry to #95 
solved in version 0.2.2
![image](https://user-images.githubusercontent.com/54232526/98507069-2865df80-225d-11eb-9421-a5112982169e.png)

**Comment by DutchmanNL** [comment]
Altready fixed in new Version ☺️
