### ISSUE TITLE
Manuel Mode Changes with Timer (like in the TADO APP)

### ISSUE THREAD

**Issue by janhp** [iobroker-community-adapters/ioBroker.tado#108]
Frage: Ich möchte gerne den Manuel Mode nutzen, allerdings nicht permament, sondern immer nur für genau 1 Stunde. In der Tado App lässt sich das einstellen. Ist es möglich dass auch über den Adapter zu machen? Danke schon mal!

**Comment by HGlab01** [comment]
Kannst es mal testen in dem du die Version direkt von
https://github.com/HGlab01/ioBroker.tado
installierst.
Vermutlich musst du zuvor den Datenpunkt
tado.0.#####.Rooms.#.overlay.termination.durationInSeconds
löschen

**Comment by janhp** [comment]
@HGlab01 Leider resetet der Mode von Timer auf Next Timeblock... scheint ein Bug zu sein.

**Comment by HGlab01** [comment]
Hallo @janhp!
Ein paar mehr Infos/Screenshot/Log wären hilfreich.
Bei mir klappt es wenn ich zB
1) Temp. manuell verändere
Resultat:
![image](https://user-images.githubusercontent.com/54232526/99186411-5ad97600-2750-11eb-92f9-91ed5cda8c6e.png)
2) wenn ich dann 
![image](https://user-images.githubusercontent.com/54232526/99186421-6fb60980-2750-11eb-9549-211229ecc172.png)
auf Timer umstelle
Resultat:
![image](https://user-images.githubusercontent.com/54232526/99186429-8bb9ab00-2750-11eb-9a8c-13364e82d45e.png)
3) Danach kann ich zB auch durationInSecond auf einen anderen Wert stellen (zB 1111)
Resultat:
![image](https://user-images.githubusercontent.com/54232526/99186461-ba378600-2750-11eb-9e53-e8049b0502f2.png)
Nimmt die 1111 und bestätigt diese auch in wenigen Sekunden

zugehörige Log-Einträge:
![image](https://user-images.githubusercontent.com/54232526/99186507-fb2f9a80-2750-11eb-82ac-9cee3e8c0d84.png)

Paar Minuten später; wie erwartet steht immer noch 1111 und TIMER; RemainingTimeInSecond hat sich dementsprechend reduziert
![image](https://user-images.githubusercontent.com/54232526/99186536-2ca86600-2751-11eb-831f-e7606397fa58.png)

Hast du bei diesen Szenario ein anderes Verhalten? Welches?
Welche Schritte hast du ausgeführt bei denen es nicht funktioniert?

**Comment by HGlab01** [comment]
PR #109 created

**Comment by DutchmanNL** [comment]
Pr wird gemerged danke !
