### ISSUE TITLE
 Disconnected from Tado cloud service

### ISSUE THREAD

**Issue by Trrw** [iobroker-community-adapters/ioBroker.tado#111]
Hallo,

ich habe die version 0.2.2 am laufen. Leider kann er sich seit heute nicht mehr mit der Tado Cloud verbinden:

<img width="1150" alt="Bildschirmfoto 2020-11-17 um 11 49 53" src="https://user-images.githubusercontent.com/24519230/99381600-9c426080-28cb-11eb-9700-870526854a2b.png">

Den Adapter neu zu installieren, hat das Problem leider nicht gelöst. Logindaten sind korrekt.

Danke!

**Comment by Trrw** [comment]
Lag anscheint an einen Verbindungsproblem von meinem Internet. Sorry

**Comment by DutchmanNL** [comment]
danke fuer die rueckmeldung !
