### ISSUE TITLE
zu viele Log Einträge bei manueller Temperturänderung

### ISSUE THREAD

**Issue by Uwe1984** [iobroker-community-adapters/ioBroker.tado#12]
Bei manueller Temperaturänderung z.B. des Datenpunktes:
tado.0.421159.Rooms.11.setting.temperature
wird im log File sehr oft ein Eintrag erzeugt. 
Wäre es möglich nur einen Eintrag zu generieren

**Auszug aus log:**
tado.0 | 2019-12-17 20:18:02.957 | info | (1196) Temperature changed for room : 11 in home : 421159to API with : 22
-- | -- | -- | --
tado.0 | 2019-12-17 20:18:02.957 | info | (1196) Room mode set : auto
tado.0 | 2019-12-17 20:18:02.957 | info | (1196) Room Temperature set : 22
tado.0 | 2019-12-17 20:18:02.955 | info | (1196) Room mode set : auto
tado.0 | 2019-12-17 20:18:02.954 | info | (1196) Room Temperature set : 22
tado.0 | 2019-12-17 20:18:02.953 | info | (1196) Room mode set : auto
tado.0 | 2019-12-17 20:18:02.953 | info | (1196) Room Temperature set : 22
tado.0 | 2019-12-17 20:18:02.951 | info | (1196) Room mode set : auto
tado.0 | 2019-12-17 20:18:02.951 | info | (1196) Room Temperature set : 22
tado.0 | 2019-12-17 20:18:02.950 | info | (1196) Room mode set : auto
tado.0 | 2019-12-17 20:18:02.950 | info | (1196) Room Temperature set : 22
tado.0 | 2019-12-17 20:18:02.949 | info | (1196) Room mode set : auto
tado.0 | 2019-12-17 20:18:02.949 | info | (1196) Room Temperature set : 22
tado.0 | 2019-12-17 20:18:02.947 | info | (1196) Room mode set : auto
tado.0 | 2019-12-17 20:18:02.947 | info | (1196) Room Temperature set : 22

`

**Comment by senger1985** [comment]
Fixed in 0.1.5 coming soon

**Comment by DutchmanNL** [comment]
https://github.com/iobroker-community-adapters/ioBroker.tado/commit/c9d36505154afe3709bb5a050bc54d63b1e3cf0c
