### ISSUE TITLE
[Feature_Request] make state "tadoMode" writable

### ISSUE THREAD

**Issue by senger1985** [iobroker-community-adapters/ioBroker.tado#13]
Please make status "tadoMode" writable to be able to change the value yourself

**Comment by janhp** [comment]
push

**Comment by HGlab01** [comment]
Hi, what do you want to get solved by just setting the state 'tadoMode' to write=true?
Maybe solving https://github.com/iobroker-community-adapters/ioBroker.tado/issues/62#issuecomment-716125331 will also solve your issue?

**Comment by DutchmanNL** [comment]
Should be fixed in next release
