### ISSUE TITLE
[Issue] open window detection

### ISSUE THREAD

**Issue by tinchenDE** [iobroker-community-adapters/ioBroker.tado#16]
The open window detection is not working.
When opening a window I get the following log entry:

> tado.0 | 2019-12-30 12:44:18.396 | error | (1525) Send this info to developer !!! { Unhandable information found in DoReadDevices : "openWindowDetected" with value : true

**Comment by DutchmanNL** [comment]
please test with 0.1.6 will be possible to install tomorrow
