### ISSUE TITLE
power off just works until next schedule change

### ISSUE THREAD

**Issue by HappyTeaFriend** [iobroker-community-adapters/ioBroker.tado#17]
When you set power = off in Rooms -> number -> setting in the past the thermostat shuts down infinite until a new command sets power on again.
Now it's just off until the schedule changes the next time.
I think the problem came with a new app version. 
![image](https://user-images.githubusercontent.com/59266574/72331216-1b697580-36b8-11ea-9cd6-5096bbe41103.png)

**Comment by Prosti95** [comment]
Yeah. Noticed the same problem. You can change this in the room settings via the app. But as it is a general setting you can't change via this adapter it takes a lot flexibility. Would be great to be able to change that via this adapter.

**Comment by DutchmanNL** [comment]
sorry but I can't find any API command to handle this happy to implement it if someone provides me the propper API

**Comment by Prosti95** [comment]
For anyone looking for a workaround: Ifttt allows you to choose a duration or set it to infinite and Tigger it via a Webhook.

![image](https://user-images.githubusercontent.com/8289793/83570377-31bc8480-a526-11ea-8f0a-9c4e1493eb91.png)

**Comment by HGlab01** [comment]
The API is:
`https://my.tado.com/api/v2/homes/[HOMENR]/zones/[ROOMNR]/overlay`
by using  **termination** in the json body.

**JSON examples:**
Data is set until next time block is reached
`{"type":"MANUAL","setting":"type":"HEATING","power":"OFF","temperature":null},"termination":"typeSkillBasedApp":"NEXT_TIME_BLOCK"}}`

Data is set forever:
`{"type":"MANUAL","setting":"type":"HEATING","power":"OFF","temperature":null},"termination":"typeSkillBasedApp":"MANUAL"}}`

Data is set for 9000 seconds
`{"type":"MANUAL","setting":"type":"HEATING","power":"OFF","temperature":null},"termination":"typeSkillBasedApp":"TIMER","durationInSeconds":9000}}`

Maybe this helps.

**Comment by HGlab01** [comment]
check https://github.com/iobroker-community-adapters/ioBroker.tado/issues/62#issuecomment-716125331
