### ISSUE TITLE
wrong label for Actual_Temperature and Humidity

### ISSUE THREAD

**Issue by t6a** [iobroker-community-adapters/ioBroker.tado#18]
wrong label for _Actual_Temperature_ and _Actual_Humidity_

<img width="526" alt="Screenshot 2020-01-18 at 01 04 52" src="https://user-images.githubusercontent.com/16940364/72654812-7ab5d700-3991-11ea-9cbc-c00402625476.png">

**Comment by DutchmanNL** [comment]
solved
