### ISSUE TITLE
Logo: white corners

### ISSUE THREAD

**Issue by t6a** [iobroker-community-adapters/ioBroker.tado#19]
Just a tiny thing: The logos background is white instead of transparent. Here a PNG file with transparent background / corners.

![tado_icon_500x500](https://user-images.githubusercontent.com/16940364/72661608-7c58bc80-39dc-11ea-9289-5f49c9ec008c.png)

<img width="537" alt="Screenshot 2020-01-18 at 10 18 32" src="https://user-images.githubusercontent.com/16940364/72661621-8c709c00-39dc-11ea-851a-fed03ecec6ab.png">

**Comment by DutchmanNL** [comment]
love it thank you ! will be part of next release https://github.com/iobroker-community-adapters/ioBroker.tado/commit/6b92be854666655b489e8d9797400050324718ca
