### ISSUE TITLE
openWindow is not working

### ISSUE THREAD

**Issue by Jogi2020** [iobroker-community-adapters/ioBroker.tado#21]
I can no longer get any values in the openWindow range.
In the LOG comes the following error message:
(881) Send this info to developer !!! { Unhandable information found in DoReadDevices : "openWindowDetected" with value : true
The openWindow area is not available in all rooms. Also, no values are visible there.
I have the impression that this is only since the last changes of Tado in the IOS APP 5.9.4 (9255)
I have adapter version 0.1.6 for ioBroker

**Comment by DutchmanNL** [comment]
Interesting, please install from git, when the error occurs I need the content of state "test_data"

this is an test-version for debug only so no new version number

**Comment by DutchmanNL** [comment]
solved
