### ISSUE TITLE
Problems in conjunction with SQL and history

### ISSUE THREAD

**Issue by Fragggy** [iobroker-community-adapters/ioBroker.tado#23]
Hi,

first, thank you for this great adapter!

I have a strange behavior in conjunction with the sql and history adapter.
For all Datapoints under tado.0. I see this in the Log:

`
sql.0 | 2020-03-26 07:58:41.996 | info | (124940) enabled logging of tado.0.408843.Rooms.8.setting.temperature, Alias=false
-- | -- | -- | --
sql.0 | 2020-03-26 07:58:40.574 | info | (124940) disabled logging of tado.0.408843.Rooms.7.Actual_Temperature
sql.0 | 2020-03-26 07:58:40.573 | info | (124940) enabled logging of tado.0.408843.Rooms.7.heatingPower, Alias=false
sql.0 | 2020-03-26 07:58:40.570 | info | (124940) enabled logging of tado.0.408843.Rooms.7.setting.temperature, Alias=false
sql.0 | 2020-03-26 07:58:39.007 | info | (124940) enabled logging of tado.0.408843.Rooms.8.heatingPower, Alias=false
sql.0 | 2020-03-26 07:58:39.004 | info | (124940) enabled logging of tado.0.408843.Rooms.8.setting.temperature, Alias=false
sql.0 | 2020-03-26 07:58:38.939 | info | (124940) enabled logging of tado.0.408843.Rooms.6.heatingPower, Alias=false
sql.0 | 2020-03-26 07:58:38.935 | info | (124940) enabled logging of tado.0.408843.Rooms.6.setting.temperature, Alias=false
sql.0 | 2020-03-26 07:58:37.905 | info | (124940) disabled logging of tado.0.408843.Rooms.7.Actual_Temperature
sql.0 | 2020-03-26 07:58:37.903 | info | (124940) enabled logging of tado.0.408843.Rooms.7.heatingPower, Alias=false
sql.0 | 2020-03-26 07:58:37.899 | info | (124940) enabled logging of tado.0.408843.Rooms.7.setting.temperature, Alias=false
sql.0 | 2020-03-26 07:58:37.555 | info | (124940) enabled logging of tado.0.408843.Rooms.5.heatingPower, Alias=false
sql.0 | 2020-03-26 07:58:37.552 | info | (124940) enabled logging of tado.0.408843.Rooms.5.setting.temperature, Alias=false
sql.0 | 2020-03-26 07:58:36.733 | info | (124940) enabled logging of tado.0.408843.Rooms.6.heatingPower, Alias=false
sql.0 | 2020-03-26 07:58:36.727 | info | (124940) enabled logging of tado.0.408843.Rooms.6.setting.temperature, Alias=false
sql.0 | 2020-03-26 07:58:36.421 | info | (124940) enabled logging of tado.0.408843.Rooms.4.heatingPower, Alias=false
sql.0 | 2020-03-26 07:58:36.416 | info | (124940) enabled logging of tado.0.408843.Rooms.4.setting.temperature, Alias=false
sql.0 | 2020-03-26 07:58:35.436 | info | (124940) enabled logging of tado.0.408843.Rooms.5.heatingPower, Alias=false
sql.0 | 2020-03-26 07:58:35.435 | info | (124940) enabled logging of tado.0.408843.Rooms.5.setting.temperature, Alias=false
sql.0 | 2020-03-26 07:58:35.328 | info | (124940) enabled logging of tado.0.408843.Rooms.3.heatingPower, Alias=false
sql.0 | 2020-03-26 07:58:35.324 | info | (124940) enabled logging of tado.0.408843.Rooms.3.setting.temperature, Alias=false
sql.0 | 2020-03-26 07:58:34.241 | info | (124940) enabled logging of tado.0.408843.Rooms.4.heatingPower, Alias=false
sql.0 | 2020-03-26 07:58:34.229 | info | (124940) enabled logging of tado.0.408843.Rooms.4.setting.temperature, Alias=false
sql.0 | 2020-03-26 07:58:33.468 | info | (124940) enabled logging of tado.0.408843.Rooms.2.heatingPower, Alias=false
sql.0 | 2020-03-26 07:58:33.464 | info | (124940) enabled logging of tado.0.408843.Rooms.2.setting.temperature, Alias=false
sql.0 | 2020-03-26 07:58:32.917 | info | (124940) enabled logging of tado.0.408843.Rooms.3.heatingPower, Alias=false
sql.0 | 2020-03-26 07:58:32.911 | info | (124940) enabled logging of tado.0.408843.Rooms.3.setting.temperature, Alias=false
sql.0 | 2020-03-26 07:58:32.192 | info | (124940) enabled logging of tado.0.408843.Rooms.1.heatingPower, Alias=false
sql.0 | 2020-03-26 07:58:32.186 | info | (124940) enabled logging of tado.0.408843.Rooms.1.setting.temperature, Alias=false
sql.0 | 2020-03-26 07:58:31.998 | info | (124940) enabled logging of tado.0.408843.Rooms.8.heatingPower, Alias=false
sql.0 | 2020-03-26 07:58:31.988 | info | (124940) enabled logging of tado.0.408843.Rooms.8.setting.temperature, Alias=false
sql.0 | 2020-03-26 07:58:31.633 | info | (124940) enabled logging of tado.0.408843.Rooms.2.heatingPower, Alias=false
sql.0 | 2020-03-26 07:58:31.625 | info | (124940) enabled logging of tado.0.408843.Rooms.2.setting.temperature, Alias=false
sql.0 | 2020-03-26 07:58:30.748 | info | (124940) disabled logging of tado.0.408843.Rooms.7.Actual_Temperature
sql.0 | 2020-03-26 07:58:30.746 | info | (124940) enabled logging of tado.0.408843.Rooms.7.heatingPower, Alias=false
sql.0 | 2020-03-26 07:58:30.720 | info | (124940) enabled logging of tado.0.408843.Rooms.7.setting.temperature, Alias=false
sql.0 | 2020-03-26 07:58:30.260 | info | (124940) enabled logging of tado.0.408843.Rooms.1.heatingPower, Alias=false
sql.0 | 2020-03-26 07:58:30.250 | info | (124940) enabled logging of tado.0.408843.Rooms.1.setting.temperature, Alias=false
sql.0 | 2020-03-26 07:58:29.507 | info | (124940) enabled logging of tado.0.408843.Rooms.6.heatingPower, Alias=false
sql.0 | 2020-03-26 07:58:29.494 | info | (124940) enabled logging of tado.0.408843.Rooms.6.setting.temperature, Alias=false
sql.0 | 2020-03-26 07:58:27.172 | info | (124940) enabled logging of tado.0.408843.Rooms.5.heatingPower, Alias=false
sql.0 | 2020-03-26 07:58:27.168 | info | (124940) enabled logging of tado.0.408843.Rooms.5.setting.temperature, Alias=false
tado.0 | 2020-03-26 07:58:26.007 | info | (124083) Overlay cleared for room : 4 in home : 408843
sql.0 | 2020-03-26 07:58:25.749 | info | (124940) enabled logging of tado.0.408843.Rooms.4.heatingPower, Alias=false
sql.0 | 2020-03-26 07:58:25.680 | info | (124940) enabled logging of tado.0.408843.Rooms.4.setting.temperature, Alias=false
sql.0 | 2020-03-26 07:58:24.192 | info | (124940) enabled logging of tado.0.408843.Rooms.3.heatingPower, Alias=false
sql.0 | 2020-03-26 07:58:24.192 | info | (124940) enabled logging of tado.0.408843.Rooms.3.setting.temperature, Alias=false
sql.0 | 2020-03-26 07:58:22.833 | info | (124940) enabled logging of tado.0.408843.Rooms.2.heatingPower, Alias=false
sql.0 | 2020-03-26 07:58:22.823 | info | (124940) enabled logging of tado.0.408843.Rooms.2.setting.temperature, Alias=false
sql.0 | 2020-03-26 07:58:21.392 | info | (124940) enabled logging of tado.0.408843.Rooms.1.heatingPower, Alias=false
sql.0 | 2020-03-26 07:58:21.379 | info | (124940) enabled logging of tado.0.408843.Rooms.1.setting.temperature, Alias=false
tado.0 | 2020-03-26 07:58:16.016 | info | (124083) Power changed for room : 4 in home : 408843 to API with : on and Temperature : 18 and mode : auto
`

this seems to be endless. 
The Data still gets writen to the DB and is usable for example in grafana.
Disabling and reanabling the logging does not solve it. 
Same happens when using history adapter  and writing to disk.

All other non tado Datapoints work fine.

Is there something special with this datapoints? 

Thank you

Regards

Dennis

**Comment by Apollon77** [comment]
This is kind of an issue in the history/sql adaqpter which is logging each time an object gets updated ... the reason is that the object is changed that often as it seems

**Comment by HGlab01** [comment]
Hi! I have the same issue but only with this adapter (which is great work!) regarding History.
Other adapters are updating as well on a regularly basis without his behavior.

My workaround was to define a trigger
_on({id: TadoTemo, change: "ne"}, function (obj) {_ 
and catch "real" changes and update in this cases an additional object and listening on this object with the History adapter.
Not that beautiful, but it works,

**Comment by DutchmanNL** [comment]
> Hi! I have the same issue but only with this adapter (which is great work!) regarding History.
> Other adapters are updating as well on a regularly basis without this behavior.
> 
> My workaround was to define a trigger
> _on({id: TadoTemo, change: "ne"}, function (obj) {_
> and catch "real" changes and update in this cases an additional object and listening on this object with the History adapter.
> Not that beautiful, but it works,

it would be easier and more efficient to just set the instance log-level on warning :)

I will make an update on the data-logger adapters to prevent this error message before releasing Tado to production but will need some time to do that.

**Comment by Fragggy** [comment]
Thank you for the workaround.
I have changed the logging to warning.

Will change back when the update is released.

Thanks

**Comment by DutchmanNL** [comment]
> Will change back when the update is released.

as mentioned it will be an update to the other adapters, thank you will create issue and link to here so we have an overview.

As the other one are heavy used, it requires large testing so will take some time 🔢

**Comment by DutchmanNL** [comment]
Fixed in source adapter
