### ISSUE TITLE
JS Fehler bei getstate type

### ISSUE THREAD

**Issue by Stormbringer11** [iobroker-community-adapters/ioBroker.tado#24]
Hallo Dutchmann,  wie im Forum besprochen

https://forum.iobroker.net/topic/25723/test-adaper-tado-v0-1-x/410

wäre es nett, wenn du den State ändern könntest damit man abrufen kann ob tado im manuellen oder auto Modus läuft. 

Danke 😉

**Comment by HGlab01** [comment]
wenn ich es richtig verstehe, dann ist das mein Workaround:

```
//wenn kein Datenpunkt vorhanden ist, dann ist es "Auto"
if (!isState(TadoOverlay, true)) {
    setState(TadoMode, 'Auto');
}

/**
 * Checks if a a given state or part of state is existing.
 * This is a workaround, as getObject() or getState() throw warnings in the log.
 * Set strict to true if the state shall match exactly. If it is false, it will add a wildcard * to the end.
 * See: https://forum.iobroker.net/topic/11354/
 * @param {string}    strStatePath     Input string of state, like 'javascript.0.switches.Osram.Bedroom'
 * @param {boolean}   [strict=false]   Optional: if true, it will work strict, if false, it will add a wildcard * to the end of the string
 * @return {boolean}                   true if state exists, false if not
 */
function isState(strStatePath, strict) {
    let mSelector;
    if (strict) {
        mSelector = $('state[id=' + strStatePath + '$]');
    } else {
        mSelector = $('state[id=' + strStatePath + ']');
    }
    if (mSelector.length > 0) {
        return true;
    } else {
        return false;
    }
};
```

**Comment by Stormbringer11** [comment]
Danke kann’s leider nicht nachvollziehen. Nehm nur Blockly her. Ich müsste das ganze auch in ein komplexeres Blockly packen.. Würd das mit Blockly auch gehen?

**Comment by HGlab01** [comment]
> Danke kann’s leider nicht nachvollziehen. Nehm nur Blockly her. Ich müsste das ganze auch in ein komplexeres Blockly packen.. Würd das mit Blockly auch gehen?

Pfu, ich denke nicht. Kann man in Blocky auch parallen JS-Code direkt einbauen? Gibt es dafür ein Werkzeug?

**Comment by Stormbringer11** [comment]
Ja könnte man schon dafür müsste man aber den Code verstehen ;-) Soweit ich den deuten kann hat er ja keinen trigger oder? Hätte es jetzt mal mit meinen DPs versucht und einem Chrontrigger als test... aber schreiben tut er nichts. Aber vermutlich hab ich einen Fehler drinnen. Den ersten Teil hab ich geändert auf, den Schluß hab ich gelassen:

`if (!isState('tado.0.63875.Rooms.3.overlay.type', true)) {
    setState('javascript.0.Test.Variable_String_2', 'Auto');
} `

Aber wie gesagt ich weiß nicht was ich da mach ;D Ist also absoluter Blindflug *g*

**Comment by HGlab01** [comment]
Hallo,

bei mir rennt dieser Code in einem CronJob, der jede Minute läuft

```
schedule("*/1 * * *", function () {
    //wenn kein Datenpunkt vorhanden ist, dann ist es "Auto"
    if (!isState(TadoOverlay, true)) {
        setState(TadoMode, 'Auto');
    }
});
```

Wichtig ist aber auch die Funktion _isState_ "abzulegen".
Dazu musst du über die [drei Punkte] (Menü) den Expertenmodus aktivieren und dort im Ordner "global" den Code ablegen.
ich hoffe den kann man dann auch aus Blocky aufrufen

```
function isState(strStatePath, strict) {
    let mSelector;
    if (strict) {
        mSelector = $('state[id=' + strStatePath + '$]');
    } else {
        mSelector = $('state[id=' + strStatePath + ']');
    }
    if (mSelector.length > 0) {
        return true;
    } else {
        return false;
    }
};
```

**Comment by flapman** [comment]
tado.0 | 2020-08-01 18:10:38.912 | error | (1958) Send this info to developer !!! { Unhandable information found in DoHome : "legacyHeatingInstallationsEnabled" with value : true
-- | -- | -- | --

**Comment by HGlab01** [comment]
could be solved with PR #98 because state would have value NULL

**Comment by DutchmanNL** [comment]
Pr meeged ☺️
