### ISSUE TITLE
Wrong variable declaration for clearZoneOverview

### ISSUE THREAD

**Issue by Coffee-lover** [iobroker-community-adapters/ioBroker.tado#27]
tado.0.xxxx.Rooms.1.overlay.clearZoneOverlay is created as number but being a button it should be boolean.

Changed my data points manualy and could solve Log-warning thereby.

**Comment by senger1985** [comment]
In my case: "Tado adapter V0.1.9"
The variable is created as boolean

**Comment by Coffee-lover** [comment]
So it seems to have been fixed in the meantime.

**Comment by HGlab01** [comment]
[changed](https://github.com/iobroker-community-adapters/ioBroker.tado/commit/fb2be6d476b7fd99b654be4b692cf0283cd09715?diff=split#diff-897bf56ded227ad643196b4b1756f57b) in v0.1.4
