### ISSUE TITLE
Tado-AC-Control

### ISSUE THREAD

**Issue by LutzHelling** [iobroker-community-adapters/ioBroker.tado#28]
I added a Tado-AC-Control - since that I see new error in my logfile corresponding with the tado adapter. See screenshot attached. These errors occur every time the adapter pulls data from the tado cloud.
![Tado-Logfile-Error](https://user-images.githubusercontent.com/58373122/83344503-225ff000-a308-11ea-8df6-062787aa54d3.png)
[logfile.txt](https://github.com/iobroker-community-adapters/ioBroker.tado/files/4707099/logfile.txt)

**Comment by HGlab01** [comment]
double entry to https://github.com/iobroker-community-adapters/ioBroker.tado/issues/30?

**Comment by DutchmanNL** [comment]
PR-Merged, 0.2.0 will be released today .... Thank you @HGlab01 !
