### ISSUE TITLE
Disconnected from Tado cloud service

### ISSUE THREAD

**Issue by jannnfe** [iobroker-community-adapters/ioBroker.tado#29]
Hey,
no connection is possible with the newest version of the adapter and iobroker

tado.0 | 2020-06-17 20:45:29.964 | error | (18827) Disconnected from Tado cloud service ..., retry in 30 seconds !
-- | -- | -- | --
tado.0 | 2020-06-17 20:45:29.961 | warn | (18827) This will be refused in future versions. Please report this to the developer.
tado.0 | 2020-06-17 20:45:29.960 | warn | (18827) The id "438872" has an invalid type!: Expected "string" or "object", received "number".

Please help me

**Comment by totocotonio** [comment]
Installiere die Version von Git, dann funzt es.
