### ISSUE TITLE
Werte häufig nicht definiert/aktualisiert

### ISSUE THREAD

**Issue by Coffee-lover** [iobroker-community-adapters/ioBroker.tado#3]
**Describe the bug**  
Ich habe einige Datenpunkte in einer Tabelle für VIS eingefügt. Diese Datenpunkte sind relativ häufig leer. In der Tabelle in VIS wird dafür "null" oder "undefined" angezeigt. Zwischen tatsächlichem Wert und dem leeren Wert schaltet die Anzeige hin und her. Grundsätzlich funktionieren die Datenpunkte also.

**Screenshots & Logfiles**  
Entsprechende Screenshots hätte ich gesichert. Leider gerade keinen Hoster zur Hand.

**Versions:**  
 - Adapter version: 0.1.1.
 - JS-Controller version: 1.5.11
 - Node version: v10.16.0

**Comment by DutchmanNL** [comment]
da einige (nicht alle) Datenpunkt ab und zu keine werte liefern (zb overlay muss. lehr. sein wen aus) setze ich diese auf expire dadurch entsteht die NULL

ich habe bereits die funtionalitaet eingebaut bestimmte werte von diesem expire aus zu schließen, um welche werte geht es dan kann ih schauen ob ich das dafuer aktivieren kan

**Comment by Coffee-lover** [comment]
Eine Temperatur, bei des es mir aufgefallen ist: 
- Away -> Minimumaway. Komischerweise
- Power -> on/off
- Mode -> Home/Away
- Actual humidity
- Actual temperature

**Comment by DutchmanNL** [comment]
probier mal bitte von GitHub diese 5 sollten jetzt bleiben. (version ungeaendert)
eventuell doch noch n Größeres problem im controller gefunden mal schauen

https://github.com/iobroker-community-adapters/ioBroker.tado/commit/cf5023de3c5b01481e5cd171d1849ceb00aa4fe7

**Comment by Coffee-lover** [comment]
Habe nochmal über Github installiert, es hat sich aber scheinbar nicht gelöst. Spannenderweise ist meist beim Laden der Seite der Wert vorhanden und kurz darauf springt "alles" auf NULL.

**Comment by DutchmanNL** [comment]
ja sieht nach nem problem im js controller aus bin noch am analysieren

**Comment by Apollon77** [comment]
Bitte mal den neuen Controller 2.0.34 versuchen

**Comment by DutchmanNL** [comment]
> Bitte mal den neuen Controller 2.0.34 versuchen

fixed mit neuen controller
