### ISSUE TITLE
Error-messages in iobroker-log (unhandable information, issue getting ZoneStates TypeError)

### ISSUE THREAD

**Issue by seiferrtalle** [iobroker-community-adapters/ioBroker.tado#30]
**Describe the bug**  
Error messages in iobroker-log - see attached logfile.

**Expected behavior**  
Error messages seem not to be critical, but should be corrected.

**Screenshots & Logfiles**  
Logfile attached.

**Versions:**  
 - JS-Controller version: 3.1.6
 - Node version: v10.22.0
 - Operating system: Raspian Buster Lite
[Errorlog_TADO_iobroker.txt](https://github.com/iobroker-community-adapters/ioBroker.tado/files/4956252/Errorlog_TADO_iobroker.txt)

**Comment by HGlab01** [comment]
in which version? Sould be fixed in 0.1.4

> **0.1.4 Fixed Clear Overlay, Open Window & log error's**
> (DutchmanNL) Fixed Clear Overlay to Boolean
> (DutchmanNL) Fixed datapoints for OpenWindow
> (DutchmanNL) Fixed setting overlay correctly for manuel temperature changes (use previous setting instead of always manual)
> (DutchmanNL) Fixed error message Cannot read property 'percentage' of undefined"

**Comment by seiferrtalle** [comment]
Adapter-Version 0.1.9, repeating the following error messages:

tado.0 | 2020-08-03 09:38:29.708 | error | (1356) Send this info to developer !!! { Unhandable information found in DoReadDevices : "commandTableUploadState" with value : "FINISHED"
-- | -- | -- | --
tado.0 | 2020-08-03 09:38:29.707 | error | (1356) Send this info to developer !!! { Unhandable information found in DoReadDevices : "accessPointWiFi" with value : {"ssid":"tado6688"}
tado.0 | 2020-08-03 09:38:21.917 | error | (1356) Send this info to developer !!! { Unhandable information found in DoHome : "legacyHeatingInstallationsEnabled" with value : true
tado.0 | 2020-08-03 09:37:20.844 | error | (1356) Issue getting ZoneStates TypeError: Cannot read property 'percentage' of undefined

**Comment by HGlab01** [comment]
First three entries should be solved in fork
https://github.com/HGlab01/ioBroker.tado
Please install/check, if it works I will send a pull request

**Comment by seiferrtalle** [comment]
Installed, seems to work. First three errors no longer reported. Issue getting ZoneStates still remaining. Thanx.

**Comment by HGlab01** [comment]
I could try to solve the other issue as well, but I cannot promise that I am able to do.
For this I would need the log in debug-mode to have an idea what is going wrong...

**Comment by DutchmanNL** [comment]
I can have a look at that one think it’s just an attribute linking but currently on holiday so not much time to verify al as I locally partial also rebuild es some parts so as usual the biggest problem : time 😢

**Comment by seiferrtalle** [comment]
Thanx guys! 👍 I did some debugging, see attached. Just changed mailadress and some names in the debuglog. ;-) Hope that helps! :-)

[20200804_Tado_DEBUG.txt](https://github.com/iobroker-community-adapters/ioBroker.tado/files/5021187/20200804_Tado_DEBUG.txt)

**Comment by HGlab01** [comment]
@seiferrtalle 
would be cool if you can test this version
https://github.com/HGlab01/ioBroker.tado/tree/HGlab01-patch-1
(I hope you can install from this path!?!)
It is not solving the ZoneStates TypeError issue but optimizing the accessPointWiFi issue.
Now you should find a channel "accessPointWiFi" und in this channel a state "ssid" with the value "tado6688".
Maybe you have to delete the existing state "accessPointWiFi" first.

**Comment by HGlab01** [comment]
ok, it did not work, so I merged to
https://github.com/HGlab01/ioBroker.tado/
Please feel free to test :-)

**Comment by seiferrtalle** [comment]
Installed. Works exactly as described: "Now you should find a channel "accessPointWiFi" und in this channel a state "ssid" with the value "tado6688".
-> so it is!

**Comment by HGlab01** [comment]
Glad to read 
Pull request https://github.com/iobroker-community-adapters/ioBroker.tado/pull/35 created

**Comment by DutchmanNL** [comment]
PR-Merged, 0.2.0 will be released today

**Comment by seiferrtalle** [comment]
Great! Thanx a lot! Regards, Ralf

Von: Dutchman <notifications@github.com>
Gesendet: Samstag, 29. August 2020 16:09
An: iobroker-community-adapters/ioBroker.tado <ioBroker.tado@noreply.github.com>
Cc: seiferrtalle <seifert.ralf@outlook.com>; Mention <mention@noreply.github.com>
Betreff: Re: [iobroker-community-adapters/ioBroker.tado] Error-messages in iobroker-log (unhandable information, issue getting ZoneStates TypeError) (#30)


PR-Merged, 0.2.0 will be released today

**Comment by DutchmanNL** [comment]
0.2.0-beta.1 will be available in admin (latest) by tomorrow morning
