### ISSUE TITLE
Unhandable information found in DoHome : "legacyHeatingInstallationsEnabled" with value : true

### ISSUE THREAD

**Issue by macstone23** [iobroker-community-adapters/ioBroker.tado#32]
There are multiple error messages in the ioBroker log:

tado.0 | 2020-07-27 15:46:53.338 | error | (18362) Send this info to developer !!! { Unhandable information found in DoHome : "legacyHeatingInstallationsEnabled" with value : true

Do you need additional information?

**Comment by HGlab01** [comment]
Same here by using adapter version 0.1.9. Before updating to v 0.1.9 no errors in the log.

JS-Controller: 3.1.6
Admin: 4.0.10
JS Script Engine: 4.6.17
Node/Node.js: 10.21.0
OS: Linux Ubuntu 18.04.3 LTS
Hardware: x64, Intel Core i3

**Comment by DutchmanNL** [comment]
Will check this evening looks like a new api attribute nothing to really worry about

**Comment by HGlab01** [comment]
Sent a pullrequest to add the new attribute
https://github.com/iobroker-community-adapters/ioBroker.tado/pull/33

**Comment by jannnfe** [comment]
Same here. Can you merge the pull request to master?

**Comment by HGlab01** [comment]
As **interims** solution you could install the fork for the pull request
https://github.com/HGlab01/ioBroker.tado
on your own risk. It works fine for me.

**Comment by jannnfe** [comment]
Can you tell me how to do this?

**Comment by HGlab01** [comment]
> Can you tell me how to do this?

1. Tab adapter
2. ![image](https://user-images.githubusercontent.com/54232526/89372466-8925cf00-d6e6-11ea-931e-18d5651fef2f.png)
3. ![image](https://user-images.githubusercontent.com/54232526/89372574-cee29780-d6e6-11ea-845c-39ae52c97f6d.png)
4. Button Install / Installieren

**Comment by CKMartens** [comment]
I installed th fork from @HGlab01 and it works fine for me

**Comment by Coffee-lover** [comment]
Same issue with me as well. Trying to use the fork. Thx, @HGlab01 .

**Comment by DutchmanNL** [comment]
updates and check of PULL request is planned for me next week, sorry for being absent for a while needed to fix some private life matters but development never stops only parks :)

**Comment by Coffee-lover** [comment]
Thx. All the best for your private matters.

**Comment by HGlab01** [comment]
> updates and check of PULL request is planned for me next week, sorry for being absent for a while needed to fix some private life matters but development never stops only parks :)

setting the right priorities is key!

**Comment by DutchmanNL** [comment]
PR-Merged, 0.2.0 will be released today .... Thank you @HGlab01 !
