### ISSUE TITLE
Info for Developer in Log

### ISSUE THREAD

**Issue by CKMartens** [iobroker-community-adapters/ioBroker.tado#34]
In ioBroker Log i found this Information:

```
tado.0 | 2020-08-05 07:20:40.674 | error | (2298) Send this info to developer !!! { Unhandable information found in DoHome : "legacyHeatingInstallationsEnabled" with value : true
-- | -- | -- | --

```

**Versions:**  
 - Adapter version: 0.1.9
 - JS-Controller version: 3.1.6
 - Node version: 10.22.0
 - Operating system: Linux Ubuntu 18.04 LTS

**Comment by HGlab01** [comment]
double entry to https://github.com/iobroker-community-adapters/ioBroker.tado/issues/32
