### ISSUE TITLE
Error in Log while refreshing - (31135) Send this info to developer !!! { Unhandable information found in DoHome : "legacyHeatingInstallationsEnabled" with value : true

### ISSUE THREAD

**Issue by Holarn** [iobroker-community-adapters/ioBroker.tado#48]
IoBroker Log throw error message: 
31135) Send this info to developer !!! { Unhandable information found in DoHome : "legacyHeatingInstallationsEnabled" with value : true

Used accessoires from Tado: 
Heating Thermostat 1x
Radiator theromstat 4x

Br
Arne

**Comment by DutchmanNL** [comment]
This schools ne fixed already, which version do you have installed ?

**Comment by Holarn** [comment]
Hi, 
I am still using 0.1.9 - I don't see the 0.2.0 version in iobroker - do I need to upgrade manually?

**Comment by DutchmanNL** [comment]
That sound that you are using the "default" repository for your adapters (which is fine as Tado is not released to stable yet)
If you want to use beta version, please switch your repository to "latest".

My suggestions always is to stay on stable if you are a regular end-user and only switch to beta if you exactly know how to troubleshoot and live with error (as other adapter update can break functionality)

Advice in this case : switch your repository temporary to latest, update the tado adapter (version 0.2.0-beta.1 will be shown)
Switch back to default again to keep all other adapters on stable version.

As long we release beta (expect to have stable release in October) this is the only propper way, by subscribing to this repository you will receive an message if new versions are released or join our Discord channel :)

https://discord.com/invite/HwUCwsH

**Comment by Holarn** [comment]
Thank you, I've just updated the adapter manually via console and it after restarting it the error does not pop up anymore.

**Comment by DutchmanNL** [comment]
> Thank you, I've just updated the adapter manually via console and it after restarting it the error does not pop up anymore.

thanks for the hint, indeed totally forget just using npm I iobroker.tado@latest does the same trick
