### ISSUE TITLE
Tado immer wieder Response 400

### ISSUE THREAD

**Issue by canim60** [iobroker-community-adapters/ioBroker.tado#56]
Hallo, bekomme seit paar Tagen im Log immer wieder reconects von Tado

`

tado.0 | 2020-09-16 22:48:14.789 | error | (2005) Disconnected from Tado cloud service ..., retry in 30 seconds !
-- | -- | -- | --
tado.0 | 2020-09-16 22:48:14.789 | error | (2005) Error in data refresh : Error: Client request error: connect ETIMEDOUT 2600:9000:2182:1400:17:7ce2:d400:93a1:443

> `aspberrypi

Platform
    linux
Betriebssystem
    linux
Architektur
    arm
CPUs
    4
Geschwindigkeit
    600 MHz
Modell
    ARMv7 Processor rev 3 (v7l)
RAM
    3.74 GB
System Betriebszeit
    4 T. 06:34:22
Node.js
    v12.18.3 (Es gibt eine neuere Version: v12.18.4)
NPM
    6.14.6
Festplatte Größe
    14.33 GB
Festplatte frei
    10.95 GB
Anzahl der Adapter
    363
Betriebszeit
    4 T. 06:34:14
Aktive Instanzen
    18
Hostname
    `raspberrypi``

>

**Comment by DutchmanNL** [comment]
Error: Client request error: connect ETIMEDOUT bedeutet das die API nicht reagiert, das kann an der internet Verbindung liegen oder der api von Tado kann ich leider nichts dran machen Wasser deutlichere log
