### ISSUE TITLE
[FeatureRequest] Temperatur ändern bis zur nächsten Planmäßigen Änderung

### ISSUE THREAD

**Issue by Hotte512** [iobroker-community-adapters/ioBroker.tado#6]
Es wäre toll simpel den Manuellen Modus wählen zu können, sprich Timer/Bis vom Benutzer beendet/bis zur nächsten automatischen Änderung...

Das scheint ja mit Mode MANUAL & Duration / Type&typeSkillBasedApp TADO_MODE & ProjectedExpiry zu funktionieren, ich konnte aber leider mit keinem der Werte arbeiten.

Danke

(Ich wollte mit dem Feiertag-script meine Büroräume gerne bis zur nächsten automatischen Änderung auf 16°C stellen, leider gelingt es mir nur bis vom Benutzer beendet.)

**Comment by DutchmanNL** [comment]
das sollte jetzt klappen,  wie folgt : 

- in der vorige version wurde der modus immer. auf manuell gesetzt

Die neue version übernimmt die jetzige Einstellung (solle also auto sein) und manuelle Temperatur.
sobald der der naestes Zeitpunkt des auto modus. erreicht wird übernimmt er wieder diese Temperatur

**Comment by HGlab01** [comment]
check https://github.com/iobroker-community-adapters/ioBroker.tado/issues/62#issuecomment-716125331
