### ISSUE TITLE
Änderungen nur bis zum nächsten Schedule möglich

### ISSUE THREAD

**Issue by Stormbringer11** [iobroker-community-adapters/ioBroker.tado#62]
Hallo Dutchmann,

ich muß jetzt leider den Issue wieder aufleben lassen:

https://github.com/iobroker-community-adapters/ioBroker.tado/issues/17

da ich den Weg über IFTTT eigentlich nicht gehen wollte. Zumal IFTTT jetzt dann eh Geld kostet...

Da das Problem früher glaub ich nicht bestand, kann das nicht mit der Änderung zusammen hängen:

https://github.com/iobroker-community-adapters/ioBroker.tado/issues/6

Aber so wie er jetzt der Adapter arbeitet haut das leider nicht hin, wenn er jede manuelle Übersteuerung von tado ändern lässt.

Wäre nett, wenn du dir das nochmal anschauen könntet. 

PS: Da ich dir leider auch keine API liefern kann, könnte ich dir als Tip nur noch geben, dass das alte HAM Plug In die Änderungen auch unbefristet übernommen hat. Vielleicht findest du als Experte in dem Code was

**Comment by HGlab01** [comment]
I added the following to #17

The API is:
https://my.tado.com/api/v2/homes/[HOMENR]/zones/[ROOMNR]/overlay
by using termination in the json body.

JSON examples:
Data is set until next time block is reached
{"type":"MANUAL","setting":"type":"HEATING","power":"OFF","temperature":null},"termination":"typeSkillBasedApp":"NEXT_TIME_BLOCK"}}

Data is set forever:
{"type":"MANUAL","setting":"type":"HEATING","power":"OFF","temperature":null},"termination":"typeSkillBasedApp":"MANUAL"}}

Data is set for 9000 seconds
{"type":"MANUAL","setting":"type":"HEATING","power":"OFF","temperature":null},"termination":"typeSkillBasedApp":"TIMER","durationInSeconds":9000}}

Maybe this helps.

**Comment by HGlab01** [comment]
I tried to solve the issue which is mentioned in this issues as well as in #6 , #17 and #78 

Please install the fork from
https://github.com/HGlab01/ioBroker.tado

Delete  (for being on the save side) the node *.Rooms.[ROOMNR].overlay.termination
After adjusting the temperature you can change
*.Rooms.[ROOMNR].overlay.termination.typeSkillBasedApp by using the values:
MANUAL --> stays unchanged until it is changed again manually
NEXT_TIME_BLOCK --> switch to Auto-mode when next time block was reached
Default-behavior (value is empty): like NEXT_TIME_BLOCK

If the fork works I will create a PR

**Comment by cortanaDE** [comment]
@HGlab01 
Oh, das ist ja toll.
Nur eine "dumme" Frage.
Wie oder was genau soll ich das jetzt installieren? 
Konsole / Git?

Lieben dank für deine Antwort.
Gruß

**Comment by Stormbringer11** [comment]
wow vielen Dank teste ich dann mal und berichte 😉👍🏻
@cortanaDe so wie ich das verstehe den Link den HGlab oben geschrieben hat über die „katze“ direkt im admin installieren

**Comment by HGlab01** [comment]
Goto Tab "Adapter", klick on

![image](https://user-images.githubusercontent.com/54232526/97138911-97214400-1759-11eb-8961-b44cea3ecdae.png)

and then

![image](https://user-images.githubusercontent.com/54232526/97139005-ca63d300-1759-11eb-8d00-6671979ad844.png)

**Comment by cortanaDE** [comment]
@HGlab01  und @Stormbringer11 

Lieben Dank für die Erklärung zur Installation. Hab lieber noch einmal nachgefragt. Da ja Git Links immer die "bösen" Links sind.
- Backup
- alte Version deinstalliert
- neue Version von Git installiert

Ging alles Problemlos und ohne Fehler.

**Comment by cortanaDE** [comment]
@HGlab01 

Habe nun den Adapter getestet und bin total happy...

Tested:

1. in ".overlay.termination.typeSkillBasedApp" einmalig "MANUAL" ausgeführt
2. in ".setting.temperature" einmalig 12 Grad ausgeführt
3. zurück gesetzt in ".overlay.clearZoneOverlay"
4. Script angepasst "Modus (MANUAL) wird gesetzt"
`setState(sTadoRoom + "overlay.termination.typeSkillBasedApp", "Manual");`
5. Script angepasst "Temperatur wird mit Verzögerung von XX Sekunden gesetzt"
`setStateDelayed(sTadoRoom + "setting.temperature"/*Temperature*/, nSetzteDefAbsenktemperatur, 5000, false);`

Beim öffnen der Kontakte wird bisher sauber der Modus "MANUAL" gesetzt.
Nach einer Verzögerung von XX Sekunden wird die Temperatur geschrieben.
Die App zeigt "Bis vom Nutzer beendet" (Unendlich).

Kontakte geschlossen = Intelligenter Modus
Bisher keine Fehler!

**Comment by HGlab01** [comment]
Happy to hear!
@DutchmanNL PR #89 ready to merge if you like it ;-)

**Comment by Stormbringer11** [comment]
Super Arbeit danke HGlab01, bei mir funktioniert es auch einwandfrei. Das Einzige was ich habe ist, dass das LOG zugespamt wird mit der Meldung:

(464880) Send this info to developer !!! { Unhandable information found in DoHome : "autoAssistFreeTrialEnabled" with value : false

**Comment by HGlab01** [comment]
Hi, this not related to my extension. That's a new attribute in the API which is provided by Tado since today.
For this a second fix is necessary --> #95

**Comment by Stormbringer11** [comment]
Ah ok, dann vielen lieben Dank für deine tolle Arbeit :o)

**Comment by cortanaDE** [comment]
Ich bekomme diesen Log Eintrag nicht. Warum?

**Comment by HGlab01** [comment]
> Ich bekomme diesen Log Eintrag nicht. Warum?
> Was ist bei dir anders?

Weil Tado offensichtlich step by step das API ausrollt.
Eventuell bekommst du die Warnung wenn du den Adapter nochmals restartest...

**Comment by cortanaDE** [comment]
lol
`8932) Send this info to developer !!! { Unhandable information found in DoHome : "autoAssistFreeTrialEnabled" with value : false`

@HGlab01   Hätte ich dich nur nicht gefragt :D

**Comment by HGlab01** [comment]
von alleine oder nach Restart Adapter?

**Comment by cortanaDE** [comment]
tatsächlich erst nach dem Restart.

**Comment by HGlab01** [comment]
@cortanaDE + @Stormbringer11 
added autoAssistFreeTrialEnabled to (temporary) fork
https://github.com/HGlab01/ioBroker.tado
Feel free to update and test/use ;-)

**Comment by cortanaDE** [comment]
@HGlab01 

Adapter wurde über Git aktualisiert.
Log ist clear. Bisher keine neuen Einträge oder sonstige Fehler.

Nice..

**Comment by Stormbringer11** [comment]
Super danke bei mir ist auch nichts mehr im LOG. @HGlab01  Der Fix mit den Blankstates ist da aber noch nicht dabei oder?

**Comment by HGlab01** [comment]
welche Blankstates?

**Comment by Stormbringer11** [comment]
ja genau das mein ich. hm, das geht bei mir noch nicht. habe aber auch nicht deinstalliert vorher... hätte man das müssen? ich probiere mit deinstallieren bei gelegenheit nochmal

**Comment by HGlab01** [comment]
es sollte reichen das Objekte *.Rooms.[ROOMNR].overlay inklusive childs zu löschen
wenn du danach von Auto auf Manuell und dann wieder auf Auto wechselst sollte binnen weniger Sekunden im State type 'null' drinnen stehen. Am besten ausprobieren, in dem du mit der Maus über den das Feld fährst und schaust ob ein Mausover erscheint mit Wert: null (in der alten Lösung kam das Mausover nicht, weil der State nicht mehr definiert war)
![image](https://user-images.githubusercontent.com/54232526/97665237-3e181f80-1a7b-11eb-9e75-f7196ce58eac.png)

**Comment by Stormbringer11** [comment]
Mh, leider klappt es bei mir nach dem löschen der Objekte noch immer nicht.

Wert null zeigt die Hoverinfo und der History Adapter zwar an:

<img width="539" alt="Bildschirmfoto 2020-10-30 um 15 33 47" src="https://user-images.githubusercontent.com/43651672/97717637-501eb000-1ac5-11eb-8232-6ddbd501fe6a.png">


Aber das Skript schmiert bei Auto trotzdem wieder ab, weil es keinen Wert bekommen kann

`

javascript.0 | 2020-10-30 15:29:01.560 | error | (418288) at Script.runInContext (vm.js:130:18)
-- | -- | -- | --
javascript.0 | 2020-10-30 15:29:01.560 | error | (418288) at script.js.1_Geraeteeinhaengpunkte.1GEP206_tado_AZ_Adapter_mit_Blank_Bugfix3:98:1
javascript.0 | 2020-10-30 15:29:01.560 | error | (418288) at ModusErmitteln (script.js.1_Geraeteeinhaengpunkte.1GEP206_tado_AZ_Adapter_mit_Blank_Bugfix3:24:28)
javascript.0 | 2020-10-30 15:29:01.560 | error | (418288) TypeError: Cannot read property 'indexOf' of null
javascript.0 | 2020-10-30 15:29:01.560 | error | (418288) ^
javascript.0 | 2020-10-30 15:29:01.560 | error | (418288) if (Modus_Adapter_Wert.indexOf('MANUA') + 1 > 0) {
javascript.0 | 2020-10-30 15:29:01.560 | error | (418288) script.js.1_Geraeteeinhaengpunkte.1GEP206_tado_AZ_Adapter_mit_Blank_Bugfix3: script.js.1_Geraeteeinhaengpunkte.1GEP206_tado_AZ_Adapter_mit_Blank_Bugfix3:24

`

**Comment by DutchmanNL** [comment]
zeig mal dein script

**Comment by Stormbringer11** [comment]
<img width="714" alt="Bildschirmfoto 2020-10-30 um 15 39 15" src="https://user-images.githubusercontent.com/43651672/97718301-14381a80-1ac6-11eb-8736-b684886a7a86.png">

Hier mal nur der relevante Ausschnitt. Oder wolltest Export. Dann muss ich aber die Daten von den States xxxen oder?

**Comment by DutchmanNL** [comment]
> <img alt="Bildschirmfoto 2020-10-30 um 15 39 15" width="714" src="https://user-images.githubusercontent.com/43651672/97718301-14381a80-1ac6-11eb-8736-b684886a7a86.png">
> 
> Hier mal nur der relevante Ausschnitt. Oder wolltest Export. Dann muss ich aber die Daten von den States xxxen oder?

waehre praktisch, gerne auch per mail an rdrozda86@gmail.com

**Comment by HGlab01** [comment]
und vielleicht auch was du eigentlich erreichen willst....

**Comment by Stormbringer11** [comment]
Der Skript schreibt eigentlich nur einen Einhängepunkt mit dem ich dann bei allen anderen Skripten und VIS weiter arbeite. Und wissen will ich ob der Modus auf Auto oder Manuell ist ;-)

Ich habs Dutchman mal gemailt.

@HGlab01 Du meinst umgekehrte Logik, nicht nach Manual abfragen sondern null? Kann ich mal probieren...

**Comment by HGlab01** [comment]
soweit ich das Blocky lese fragst du es komplizierter ab
Bei mir geht es in beide Richtungen, auch mit
```
if (getState('tado.0.####.Rooms.1.overlayType').val == '"MANUAL"') {
    log('MANUAL');
}
else {
    log('AUTO');
}
```

Was mir auffällt: du suchst nach MANUAL, im speziellen Dataset steht jedoch "MANUAL"  (also auch die Doppelhochkomma sind in dem Feld gespeichert!) 
![image](https://user-images.githubusercontent.com/54232526/97721041-426b2980-1ac9-11eb-9e2f-96b937664f7d.png)

**Comment by Stormbringer11** [comment]
Das war Verzweiflung mit dem "enthalten im Text" aber jetzt scheint es zu klappen. Ich teste nachher mal weiter.
Aber schon mal super, danke nochmal :o)
Aber vom Grundverständnis her... Dachte ich Blick bei Blockly zumindest ein bisschen durch... Müsste es unterm Strich nicht auf das Selbe kommen ob ich so abfrage oder ob es im Text enthalten ist?

**Comment by DutchmanNL** [comment]
> Das war Verzweiflung mit dem "enthalten im Text" aber jetzt scheint es zu klappen. Ich teste nachher mal weiter.
> Aber schon mal super, danke nochmal :o)
> Aber vom Grundverständnis her... Dachte ich Blick bei Blockly zumindest ein bisschen durch... Müsste es unterm Strich nicht auf das Selbe kommen ob ich so abfrage oder ob es im Text enthalten ist?

nein da der wert null sein kann und null ist kein wert den man auslesen kan und dadurch knallt dein script :)

**Comment by HGlab01** [comment]
ohne https://github.com/HGlab01/ioBroker.tado/pull/7 würde auch getState() knallen, denn da ist der State dann generell nicht mehr valide. Daher würde ich es (natürlich) gut finden den PR einzubauen ;-)

**Comment by Stormbringer11** [comment]
Also lest er praktisch nur aus, wenn ich "im Text enthalten" nehme und sonst nicht?

Der Fix ist auf alle Fälle hammer damit kann man Leben ;-) Bitte unbedingt einbauen sonst schmiert ja ständig alles ab

**Comment by HGlab01** [comment]
in Blockysprache müsste es so aussehen:
![image](https://user-images.githubusercontent.com/54232526/97722878-734c5e00-1acb-11eb-83c9-294c59cc24a0.png)

**Comment by Stormbringer11** [comment]
Danke wieder was dazu gelernt, danke ;o)

**Comment by Stormbringer11** [comment]
Finde den Adapter nach den beiden Fixes jetzt richtig gut und hätte minimum stable verdient, oder war er das vorher schon?

**Comment by janhp** [comment]
Frage: Ich möchte gerne den Manuel Mode nutzen, allerdings nicht permament, sondern immer nur für genau 1 Stunde. In der Tado App lässt sich das einstellen. Ist es möglich dass auch über den Adapter zu machen? Danke schon mal!

**Comment by cortanaDE** [comment]
@janhp 
Wo genau kannst du in der tado App den manuellen Modus auf eine Stunde begrenzen?

**Comment by janhp** [comment]
@cortanaDE Settings --> Rooms & Devices --> Dann auf einen Raum klicken --> Manuel Timer [hier die Zeit einstellen]

**Comment by cortanaDE** [comment]
@janhp 
Ahh.. ok. Habe ich noch nicht für voll genommen  ;D

Wenn du das haben möchtest dann hat das aber nichts mit dem Adapter selbst zu tun sondern vielmehr mit deinen Scripten.

Das müsste dann so laufen, dass du 
- wenn beispielsweise dein Fensterkontakt ein offenes Fenster meldet, dann deine Temperatur abgesenkt wird und du in deinem Script einen Timer von xxx Sekunden setzt. Danach wird dann wieder der intelligente Modus angeschaltet.

So in der Art

**Comment by HGlab01** [comment]
HAllo @janhp!
> Frage: Ich möchte gerne den Manuel Mode nutzen, allerdings nicht permament, sondern immer nur für genau 1 Stunde. In der Tado App lässt sich das einstellen. Ist es möglich dass auch über den Adapter zu machen? Danke schon mal!

Ja, das geht. Ich habs mal gerade kurz das API ausprobiert, das kann man im Adapter implementieren... Ist aber ein wenig Arbeit...
Kannst du mal bitte ein getrenntes Issue aufmachen und ich kann mir das mal in den nächsten Tagen/Wochen ansehen und einen PR erstellen.

**Comment by DutchmanNL** [comment]
@HGlab01 kan man dan in der API eine zeit mitgeben oder muessen wir das im adapter loesen und nach x zeit zurueck setzen ?

**Comment by HGlab01** [comment]
Das kann man in der API mitgeben (sonst würde ich es auch meiner Meinung nach nicht im Adapter implementieren). Es ist aber ein TADO Feature.

Erster Prototyp sieht schon recht gut aus:
https://github.com/HGlab01/ioBroker.tado/compare/master...HGlab01:add-durationInSeconds

**Comment by DutchmanNL** [comment]
> Das kann man in der API mitgeben (sonst würde ich es auch meiner Meinung nach nicht im Adapter implementieren). Es ist aber ein TADO Feature.
> 
> Erster Prototyp sieht schon recht gut aus:
> [HGlab01/ioBroker.tado@master...HGlab01:add-durationInSeconds](https://github.com/HGlab01/ioBroker.tado/compare/master...HGlab01:add-durationInSeconds)

super sehr nice, ich wollte die Logik auch nicht im adapter wegen reboot etc.....
wen wir uns um code redesign kümmern (siehe auch meine Nachricht auf discord) muessen wir ein queuing einbauen damit diese Datensätze auf einmal in der APU übertragen werden schätze ich mal (jetzt ist jeder state change ein separater Aufruf)

Weis (noch) nicht ob die API das kan meine aber wohl da diese die komplette JSON verarbeitet (to be investigativ)

**Comment by janhp** [comment]
habe ein issue dazu erstellt. danke für die implementierung!

**Comment by HGlab01** [comment]
follow up at #108

**Comment by DutchmanNL** [comment]
Solved in Next release
