### ISSUE TITLE
error | (4256) Send this info to developer !!!

### ISSUE THREAD

**Issue by Doreinie** [iobroker-community-adapters/ioBroker.tado#66]
Hallo, im iobroker Log bekomme ich diese Meldung.
allerdings scheinen alle 8 Tado Thermostate zu funktionieren. Temperatur lässt sich einstellen und Einstellungen im iobroker kommen am Thermostat an.
Die Meldung sagt ich solle diese Info hier mit einbrigen was ich gerne mach.
Ach wäre es schön wenn die Fehlermeldung abgestellt werden könnte.
Danke!

tado.0 | 2020-09-28 12:43:10.015 | error | (4256) Send this info to developer !!! { Unhandable information found in DoHome : "incidentDetection" with value : {"supported":false,"enabled":false}
-- | -- | -- | --

**Comment by DutchmanNL** [comment]
danke, da hat die api wohl einen neues Attribute bekomme schaue ich mir heute Abend an.
Kommt das bei jedem API Abruf oder nur sporadisch ?

**Comment by hilde0407** [comment]
Bei mir kommt ebenfalls dieser Log Eintrag, offensichtlich bei jedem API Abruf!
`tado.0 | 2020-09-28 13:40:07.447 | error | (22519) Send this info to developer !!! { Unhandable information found in DoHome : "incidentDetection" with value : {"supported":false,"enabled":false}
-- | -- | -- | --
`

**Comment by hilde0407** [comment]
Es sieht auch so aus, das nicht alle Befehle ausgeführt werden! Ich habe die Thermostatgruppe Wohnzimmer, bestehend aus 2 Thermostaten. Wenn ich die Temperatur der Gruppe über den Adapter ändere, kommt die Änderung nur bei einem Thermostat an.

**Comment by Doreinie** [comment]
die Error-Meldung kommt so jede Minute.

**Comment by HGlab01** [comment]
I tried to add the new attribute incidentDetection
Would be cool if you can install the fork
https://github.com/HGlab01/ioBroker.tado
If it works, I will create a PR

**Comment by HGlab01** [comment]
PR https://github.com/iobroker-community-adapters/ioBroker.tado/pull/67 created

**Comment by DutchmanNL** [comment]
@HGlab01 

Cool Thank you! Is it just a boolean value ?
We need to add the Attribute Definitions toi

https://github.com/iobroker-community-adapters/ioBroker.tado/blob/master/lib/state_attr.js

**Comment by HGlab01** [comment]
Yes, it is boolean:
"incidentDetection":{"supported":false,"enabled":false}

**Comment by DutchmanNL** [comment]
included In final 0.2.0

https://github.com/iobroker-community-adapters/ioBroker.tado/commit/efdbd2dd4d88a381267cea988fca7fbad20702ef
