### ISSUE TITLE
(18432) { Unhandable information found in DoHome : "incidentDetection" with value : {"supported":true,"enabled":false}

### ISSUE THREAD

**Issue by oggy79** [iobroker-community-adapters/ioBroker.tado#69]
(18432) Send this info to developer !!! { Unhandable information found in DoHome : "incidentDetection" with value : {"supported":true,"enabled":false}

**Comment by DutchmanNL** [comment]
already reported (and working on PR) in : 

https://github.com/iobroker-community-adapters/ioBroker.tado/issues/66
https://github.com/iobroker-community-adapters/ioBroker.tado/pull/67

**Comment by DutchmanNL** [comment]
fixed In final 0.2.0

https://github.com/iobroker-community-adapters/ioBroker.tado/commit/efdbd2dd4d88a381267cea988fca7fbad20702ef
