### ISSUE TITLE
Fehlermeldung "Unhandable information found in DoHome : "boilerId" im LOG

### ISSUE THREAD

**Issue by Coffee-lover** [iobroker-community-adapters/ioBroker.tado#7]
Hallo zusammen,

unter Version 0.1.2. (JS Controller 2.0.39, Node.js v10.17.0) taucht bei mir im 2-3 Minutentakt folgende Fehlermeldung im LOG auf:

(13682) Send this info to developer !!! { Unhandable information found in DoHome : "boilerId" with value : 4469
![image](https://user-images.githubusercontent.com/34901346/68111290-108fa900-feef-11e9-9c41-7f7905c3fa2f.png)

VG

**Comment by rehmosch** [comment]
Hey, schon eine Lösung gefunden? Kann alle Werte Live auslesen und eigentlich funktioniert es. Jedoch erhalte ich die Fehlermeldung im Log im Minutentakt ;(

Danke

**Comment by DutchmanNL** [comment]
fixed in 0.1.3 https://github.com/iobroker-community-adapters/ioBroker.tado/commit/3c8c09cae53712b1cc34c80853d8e38c1eb1114a
