### ISSUE TITLE
Unhandable information found in DoHome : "incidentDetection"

### ISSUE THREAD

**Issue by drpepperDE** [iobroker-community-adapters/ioBroker.tado#72]
Hallo, after i added the ecovacs adapter to iobroker, i will get this los entry

tado.0 | 2020-10-01 21:32:14.787 | error | (767) Send this info to developer !!! { Unhandable information found in DoHome : "incidentDetection" with value : {"supported":true,"enabled":false}
-- | -- | -- | --

**Comment by HGlab01** [comment]
Would be cool to get some meta data of your system like the installed adapter version of Tado-adapter.
I guess you are using adapter version less than 0.2.0.
Please install this version and verify the result.

**Comment by drpepperDE** [comment]
Good morning,

i use the version 0.2.0-beta.1 of the tado adapter.
i think the error would come after i installed the recommend packages from the mrbungle64/ioBroker.ecovacs-deebot github-side https://github.com/mrbungle64/ioBroker.ecovacs-deebot <https://github.com/mrbungle64/ioBroker.ecovacs-deebot>

all my adapters are on the latest available version. 
i’m new in iobroker, where can i get the meta data???

my iobroker run in an docker container on my openmediavault intsallation on my qnap 509

let me know if you need more information.

the tado adatper works fine in spite of the error… thank you for the great job!

**Comment by HGlab01** [comment]
as stated..
Please update to version 0.2.0
![image](https://user-images.githubusercontent.com/54232526/94896193-2e61e700-048d-11eb-8b54-9016d08ab0ef.png)

**Comment by DutchmanNL** [comment]
This command is Bad 
sudo npm install canvas --unsafe-perm=true

Enter  console, 
stop iobroker 
and the  run 
iobroker fix 

Endige the proper Adapter Version is installer it Must be 0.2.0 and Not 0.2.0-xxx.xx

**Comment by drpepperDE** [comment]
thanks after i install 0.2.0 the error would be fine.
the adapter at iobroker doesn't show me 0.2.0, i have to uninstall it und get it new from github.

i could not stop iobroker 

root@nas:/opt/iobroker# iobroker stop
iobroker controller daemon is not running

root@nas:/opt/iobroker# iobroker status
iobroker is running on this host.

At least one iobroker host is running.

Objects type: file
States  type: file

root@nas:/opt/iobroker# systemctl stop iobroker
bash: systemctl: Kommando nicht gefunden.

**Comment by DutchmanNL** [comment]
Root@nas ? Do you use docker or what is your base system?

**Comment by drpepperDE** [comment]
Yes I use docker for iobroker, and docker run on openmedivault on my nas.
I use the terminal in the iobroker portainer

**Comment by DutchmanNL** [comment]
> Yes I use docker for iobroker, and docker run on openmedivault on my nas. I use the terminal in the iobroker portainer
> […](#)

you should follow the docker guide than and use 
pkill io

instead of iobroker stop

**Comment by drpepperDE** [comment]
thank you, i'm not that good at linux.
i fixed it with your help!!
