### ISSUE TITLE
error message in log - Unhandable information found in DoHome

### ISSUE THREAD

**Issue by Tobi0508** [iobroker-community-adapters/ioBroker.tado#77]
Hello i got the following message in my iobroker log:

(32350) Send this info to developer !!! { Unhandable information found in DoHome : "incidentDetection" with value : {"supported":true,"enabled":false}

iobroker tado adapter version: 0.2.0-beta.1

Can you eleminate this error message. it comes every second.

Thanks
Tobi

**Comment by HGlab01** [comment]
Please update to version 0.2.0  (no longer beta)
![image](https://user-images.githubusercontent.com/54232526/95305361-27204c00-0886-11eb-9aec-bdf169058d04.png)

**Comment by Tobi0508** [comment]
Hi, thanks for this really quick answer. The 0.2.0 without beta was not offered vor me. I have uninstalle the wrong version and reinstall the real 0.2.0 and it works.

Thanks a lot
Tobi

**Comment by DutchmanNL** [comment]
i am busy unpublishing the old versions but currently without luck :/
