### ISSUE TITLE
problem mit tado Adapter / Api und termination.typ:"MANUAL" und den "TADO_MODE"

### ISSUE THREAD

**Issue by cortanaDE** [iobroker-community-adapters/ioBroker.tado#78]
Hallöchen Dutch...

Hier nun mein Problem mit dem Adapter.
Ich setzte im Adapter den Wert "setting.temperature" auf z.B. 12 Grad manuell (oder auf aus)
Der Adapter geht dann nicht wie er sollte in den Manuellen Modus sondern schaltet nur den nächsten Zeitblock.

Mir ist aufgefallen, dass die Werte "termination.typ" und "termination.typeskillbasedapp" nicht die richtigen Modi zurück melden.
Beide Werte sollten auf  "MANUAL" gesetzt werden. Somit setzt tado die Heizung auf "Unendlich" bis der "clearZoneOverlay" wieder in den Zeitplan zurück wechselt.

Die manuelle Änderung der Temperatur setzt allerdings den Wert "TADO_MODE". Hier geht die Steuerung allerdings in den nächsten Zeitblock.

Schau doch mal bitte ob du die beiden "termination" Mods anpassen kannst.

![44](https://user-images.githubusercontent.com/72450886/95510694-a01ec100-09b6-11eb-9337-a967998e0481.JPG)
![66](https://user-images.githubusercontent.com/72450886/95510700-a14fee00-09b6-11eb-9f55-bc697e53f962.JPG)

**Comment by HGlab01** [comment]
Tado verhält sich beim Adapter genau so wie es in Tado eingestellt ist. Ich vermute bei dir ist Tado (Einstellungen/Raum) so eingestellt:
![image](https://user-images.githubusercontent.com/54232526/95543990-44762700-09fa-11eb-8b98-bb0c9ad8e76f.png)

Wenn man im Adapter mehr unterstützen will, dann müsste man termination.typeSkillBasedApp im API unterstützen, siehe dazu #17

**Comment by cortanaDE** [comment]
tado ist richtig in der App eingestellt. Das ganze lief auch bereits schon einmal richtig. So wie es aussieht bin ich auch nicht der einzige mit dem Problem.

**Hier ist die passende App Einstellung:**

![20201007_223724](https://user-images.githubusercontent.com/72450886/95545317-db90ae00-09fd-11eb-81c2-a1fab08d74c3.jpg)

**Hier ist das was passiert wenn ich wie oben die Temperatur manuell anpasse:**

![Screenshot_20201007-230445_tado (1)](https://user-images.githubusercontent.com/72450886/95545557-7e492c80-09fe-11eb-83a8-401c5dd2c867.jpg)

Was meinst du mit "im API unterstützen" ?
Ich denke auch, dass es genau an diesen Werten liegt "termination.type" und "termination.typeSkillBasedApp.

**Comment by HGlab01** [comment]
Wollte damit nur sagen, dass man es somit beim Adapter beim Call des APIs berücksichtigen müsste.

**Comment by HGlab01** [comment]
check https://github.com/iobroker-community-adapters/ioBroker.tado/issues/62#issuecomment-716125331

**Comment by DutchmanNL** [comment]
https://github.com/iobroker-community-adapters/ioBroker.tado/commit/f32410b79c143534a081a3b1733533fc7537b79d
