### ISSUE TITLE
Fehlermeldung Unhandable information found in DoReadDevices : "openWindowDetected" with value : true

### ISSUE THREAD

**Issue by Coffee-lover** [iobroker-community-adapters/ioBroker.tado#8]
Hi,

in meinem Log tauchte gerade folgende Fehlermeldung auf:

`(856) Send this info to developer !!! { Unhandable information found in DoReadDevices : "openWindowDetected" with value : true
`

VG

**Comment by DutchmanNL** [comment]
ich werde diesen abmelden in der niesten version, interessant wird das die wirklich auf device niveau ist also nicht dem raum ....

**Comment by DutchmanNL** [comment]
fixed 0.1.3 https://github.com/iobroker-community-adapters/ioBroker.tado/commit/3c8c09cae53712b1cc34c80853d8e38c1eb1114a
