### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by janhp** [iobroker-community-adapters/ioBroker.tado#82]
Dear dev. can you please fix this bug?

![bug](https://user-images.githubusercontent.com/71586781/95987904-599eeb80-0e28-11eb-8dd4-c915ea872c09.png)

**Comment by L-C-P** [comment]
As I can see it, it's already fixed in version 0.2.0. @DutchmanNL Maybe the missing "mappings" should be logged as warning?

**Comment by DutchmanNL** [comment]
> As I can see it, it's already fixed in version 0.2.0. @DutchmanNL Maybe the missing "mappings" should be logged as warning?

aggree, have to adopt my logic from other missing states logics this should be a warning not a error

**Comment by L-C-P** [comment]
@DutchmanNL I am just implementing a set nextOverlayType, should I change error to warning in all places? Then it will be included in my PR?

**Comment by DutchmanNL** [comment]
> @DutchmanNL I am just implementing a set nextOverlayType, should I change error to warning in all places? Then it will be included in my PR?

source would be cool as quick fix at least. I see here that I have several functions which are handling the error in this way which should be optimized to an centralized function but we can do that later and I will adopt a function I use in other adapters to making it manageable

**Comment by L-C-P** [comment]
I will test my changes today. If there are no problems on my site, I will create a PR tomorrow, that will include the change from error to warn.

**Comment by DutchmanNL** [comment]
https://github.com/iobroker-community-adapters/ioBroker.tado/commit/f32410b79c143534a081a3b1733533fc7537b79d
