### ISSUE TITLE
Issue getting ZoneStates TypeError: Cannot read property 'percentage' of undefined

### ISSUE THREAD

**Issue by sequ3ster** [iobroker-community-adapters/ioBroker.tado#88]
Hallo zusammen,

ich setze den Tado Adapter 0.2.1 ein und möchte damit zwei Smarte Klimaanlagen-Steuerung V3+ steuern.
Das Log im iobroker läuft aber mit dieser Meldung voll.

Hello everyone,

i am using the Tado Adapter 0.2.1 and want to control two Smart AC Control V3+ with it.
But the log in the iobroker runs full with this message.

![image](https://user-images.githubusercontent.com/30301647/97110544-2ab33000-16da-11eb-808a-b2cc8746a59a.png)

**Comment by HGlab01** [comment]
Can you please dump what is stored in
*._info.JSON_response.Stage_09_ZoneStates_data_#
where # is 1 to number of tado-rooms

**Comment by brasax** [comment]
Same here:

{"tadoMode":"HOME","geolocationOverride":false,"
geolocationOverrideDisableTime":null,"preparation":null,"setting":{"type
":"HEATING","power":"ON","temperature":{"celsius":22,"fahrenheit":71.6}}
,"overlayType":null,"overlay":null,"openWindow":null,"nextScheduleChange
":{"start":"2020-11-16T17:00:00Z","setting":{"type":"HEATING","power":"
ON","temperature":{"celsius":21,"fahrenheit":69.8}}},"nextTimeBlock":{"
start":"2020-11-16T17:00:00.000Z"},"link":{"state":"ONLINE"},"
activityDataPoints":{"heatingPower":{"type":"PERCENTAGE","percentage":0,
"timestamp":"2020-11-16T14:00:19.056Z"}},"sensorDataPoints":{"
insideTemperature":{"celsius":23.22,"fahrenheit":73.8,"timestamp":"2020-
11-16T13:58:03.593Z","type":"TEMPERATURE","precision":{"celsius":0.1,"
fahrenheit":0.1}},"humidity":{"type":"PERCENTAGE","percentage":53.5,"
timestamp":"2020-11-16T13:58:03.593Z"}}}

{"tadoMode":"HOME","geolocationOverride":false,"
geolocationOverrideDisableTime":null,"preparation":null,"setting":{"type
":"HEATING","power":"OFF","temperature":null},"overlayType":"MANUAL","
overlay":{"type":"MANUAL","setting":{"type":"HEATING","power":"OFF","
temperature":null},"termination":{"type":"MANUAL","typeSkillBasedApp":"
MANUAL","projectedExpiry":null}},"openWindow":null,"nextScheduleChange":
{"start":"2020-11-16T17:00:00Z","setting":{"type":"HEATING","power":"ON"
,"temperature":{"celsius":20,"fahrenheit":68}}},"nextTimeBlock":{"start"
:"2020-11-16T17:00:00.000Z"},"link":{"state":"ONLINE"},"
activityDataPoints":{"heatingPower":{"type":"PERCENTAGE","percentage":0,
"timestamp":"2020-11-16T13:58:34.131Z"}},"sensorDataPoints":{"
insideTemperature":{"celsius":22.41,"fahrenheit":72.34,"timestamp":"2020
-11-16T14:04:05.687Z","type":"TEMPERATURE","precision":{"celsius":0.1,"
fahrenheit":0.1}},"humidity":{"type":"PERCENTAGE","percentage":48.7,"
timestamp":"2020-11-16T14:04:05.687Z"}}}

{"tadoMode":"HOME","geolocationOverride":false,"
geolocationOverrideDisableTime":null,"preparation":null,"setting":{"type
":"HEATING","power":"ON","temperature":{"celsius":21,"fahrenheit":69.8}}
,"overlayType":null,"overlay":null,"openWindow":null,"nextScheduleChange
":{"start":"2020-11-16T15:25:00Z","setting":{"type":"HEATING","power":"
ON","temperature":{"celsius":18,"fahrenheit":64.4}}},"nextTimeBlock":{"
start":"2020-11-16T15:25:00.000Z"},"link":{"state":"ONLINE"},"
activityDataPoints":{"heatingPower":{"type":"PERCENTAGE","percentage":0,
"timestamp":"2020-11-16T13:59:54.628Z"}},"sensorDataPoints":{"
insideTemperature":{"celsius":22.38,"fahrenheit":72.28,"timestamp":"2020
-11-16T14:04:49.539Z","type":"TEMPERATURE","precision":{"celsius":0.1,"
fahrenheit":0.1}},"humidity":{"type":"PERCENTAGE","percentage":47.4,"
timestamp":"2020-11-16T14:04:49.539Z"}}}

{"tadoMode":"HOME","geolocationOverride":false,"
geolocationOverrideDisableTime":null,"preparation":null,"setting":{"type
":"HEATING","power":"OFF","temperature":null},"overlayType":"MANUAL","
overlay":{"type":"MANUAL","setting":{"type":"HEATING","power":"OFF","
temperature":null},"termination":{"type":"MANUAL","typeSkillBasedApp":"
MANUAL","projectedExpiry":null}},"openWindow":null,"nextScheduleChange":
{"start":"2020-11-16T19:00:00Z","setting":{"type":"HEATING","power":"ON"
,"temperature":{"celsius":20,"fahrenheit":68}}},"nextTimeBlock":{"start"
:"2020-11-16T19:00:00.000Z"},"link":{"state":"ONLINE"},"
activityDataPoints":{"heatingPower":{"type":"PERCENTAGE","percentage":0,
"timestamp":"2020-11-16T14:05:45.724Z"}},"sensorDataPoints":{"
insideTemperature":{"celsius":21.55,"fahrenheit":70.79,"timestamp":"2020
-11-16T13:58:23.819Z","type":"TEMPERATURE","precision":{"celsius":0.1,"
fahrenheit":0.1}},"humidity":{"type":"PERCENTAGE","percentage":50.6,"
timestamp":"2020-11-16T13:58:23.819Z"}}}

{"tadoMode":"HOME","geolocationOverride":false,"
geolocationOverrideDisableTime":null,"preparation":null,"setting":{"type
":"HEATING","power":"ON","temperature":{"celsius":21,"fahrenheit":69.8}}
,"overlayType":null,"overlay":null,"openWindow":null,"nextScheduleChange
":{"start":"2020-11-16T17:00:00Z","setting":{"type":"HEATING","power":"
ON","temperature":{"celsius":23,"fahrenheit":73.4}}},"nextTimeBlock":{"
start":"2020-11-16T17:00:00.000Z"},"link":{"state":"ONLINE"},"
activityDataPoints":{"heatingPower":{"type":"PERCENTAGE","percentage":0,
"timestamp":"2020-11-16T13:50:18.665Z"}},"sensorDataPoints":{"
insideTemperature":{"celsius":22.82,"fahrenheit":73.08,"timestamp":"2020
-11-16T13:50:36.742Z","type":"TEMPERATURE","precision":{"celsius":1,"
fahrenheit":1}},"humidity":{"type":"PERCENTAGE","percentage":52.5,"
timestamp":"2020-11-16T13:50:36.742Z"}}}

{"tadoMode":"HOME","geolocationOverride":true,"
geolocationOverrideDisableTime":"2020-11-16T18:00:00Z","preparation":
null,"setting":{"type":"AIR_CONDITIONING","power":"OFF"},"overlayType":"
MANUAL","overlay":{"type":"MANUAL","setting":{"type":"AIR_CONDITIONING",
"power":"OFF"},"termination":{"type":"MANUAL","typeSkillBasedApp":"
MANUAL","projectedExpiry":null}},"openWindow":null,"nextScheduleChange":
{"start":"2020-11-16T18:00:00Z","setting":{"type":"AIR_CONDITIONING","
power":"ON","mode":"COOL","temperature":{"celsius":20,"fahrenheit":68},"
fanSpeed":"MIDDLE"}},"nextTimeBlock":{"start":"2020-11-16T18:00:00.000Z"
},"link":{"state":"ONLINE"},"activityDataPoints":{"acPower":{"timestamp"
:"2020-10-27T21:12:32.315Z","type":"POWER","value":"OFF"}},"
sensorDataPoints":{"insideTemperature":{"celsius":20.78,"fahrenheit":69.
4,"timestamp":"2020-11-16T13:52:54.953Z","type":"TEMPERATURE","precision
":{"celsius":0.1,"fahrenheit":0.1}},"humidity":{"type":"PERCENTAGE","
percentage":45.2,"timestamp":"2020-11-16T13:52:54.953Z"}}}

**Comment by HGlab01** [comment]
Hi @brasax!
I did a best guess. Can you please test by installing from
https://github.com/HGlab01/ioBroker.tado
Thanks!

**Comment by brasax** [comment]
Version is still the same, correct? 

If so, nothing changed. Same issue:

tado.0 | 2020-11-16 21:18:13.258 | error | (17776) Issue getting ZoneStates TypeError: Cannot read property 'percentage' of undefined
-- | -- | -- | --
tado.0 | 2020-11-16 21:17:32.775 | error | (17776) Issue getting ZoneStates TypeError: Cannot read property 'percentage' of undefined
tado.0 | 2020-11-16 21:16:52.740 | error | (17776) Issue getting ZoneStates TypeError: Cannot read property 'percentage' of undefined
tado.0 | 2020-11-16 21:16:12.100 | error | (17776) Issue getting ZoneStates TypeError: Cannot read property 'percentage' of undefined

**Comment by HGlab01** [comment]
yes, same version. It only happens by using TADO AC (not Heating) therefore it is fishing in the dark for me.
I added one log entry that should help me to understand it better.
Can you please install again?

**Comment by brasax** [comment]
where can I find the log?

BTW thanks for your support!

**Comment by HGlab01** [comment]
should be in the standard log tab

**Comment by brasax** [comment]
Unfortunately not. 

I did install it from the admin gui. Maybe thats the issue? Should I do it manually?

**Comment by HGlab01** [comment]
It should work if you use the "cat" and using the URL above.
I added one more LOG-line which should be shown after
 Initialisation finished, connected to Tado Cloud service refreshing every : 
and looks like: "SPECIAL VERSION!"

Would be cool if you can try

**Comment by brasax** [comment]
here is the output from the log:

  |   |   |  
-- | -- | -- | --
tado.0 | 2020-11-16 21:43:22.680 | error | (18972) Issue getting ZoneStates TypeError: Cannot read property 'percentage' of undefined
tado.0 | 2020-11-16 21:42:43.743 | info | (18972) Initialisation finished, connected to Tado Cloud service refreshing every : 30 seconds
tado.0 | 2020-11-16 21:42:42.918 | error | (18972) Issue getting ZoneStates TypeError: Cannot read property 'percentage' of undefined
tado.0 | 2020-11-16 21:42:34.097 | info | (18972) Connected to Tado cloud, initialyzing ...
tado.0 | 2020-11-16 21:42:33.522 | info | (18972) starting. Version 0.2.2 in /opt/iobroker/node_modules/iobroker.tado, node: v14.15.0, js-controller: 3.1.6

**Comment by HGlab01** [comment]
strange! Maybe you have to uninstall the adapter first.

**Comment by brasax** [comment]
Unfortunately still the same. Uninstalled, installed, set credentials.


tado.0 | 2020-11-16 21:55:39.057 | info | (19338) Initialisation finished, connected to Tado Cloud service refreshing every : 30 seconds
-- | -- | -- | --
tado.0 | 2020-11-16 21:55:38.264 | error | (19338) Issue getting ZoneStates TypeError: Cannot read property 'percentage' of undefined
tado.0 | 2020-11-16 21:55:28.180 | info | (19338) Connected to Tado cloud, initialyzing ...
tado.0 | 2020-11-16 21:55:27.630 | info | (19338) starting. Version 0.2.2 in /opt/iobroker/node_modules/iobroker.tado, node: v14.15.0, js-controller: 3.1.6
tado.0 | 2020-11-16 21:54:44.997 | info | (19315) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
tado.0 | 2020-11-16 21:54:44.997 | info | (19315) terminating
tado.0 | 2020-11-16 21:54:44.996 | info | (19315) cleaned everything up...
tado.0 | 2020-11-16 21:54:44.996 | info | (19315) Got terminate signal TERMINATE_YOURSELF
tado.0 | 2020-11-16 21:54:44.950 | error | (19315) *** Adapter deactivated, credentials missing in Adaptper Settings !!! ***
tado.0 | 2020-11-16 21:54:44.939 | info | (19315) starting. Version 0.2.2 in /opt/iobroker/node_modules/iobroker.tado, node: v14.15.0, js-controller: 3.1.6

**Comment by brasax** [comment]
now it worked:


  |   |   |  
-- | -- | -- | --
tado.0 | 2020-11-16 21:59:20.479 | info | (19488) SPECIAL VERSION!
tado.0 | 2020-11-16 21:59:20.479 | info | (19488) Initialisation finished, connected to Tado Cloud service refreshing every : 30 seconds
tado.0 | 2020-11-16 21:59:19.674 | info | (19488) TEST AIRCONDITION: undefined
tado.0 | 2020-11-16 21:59:18.327 | info | (19488) TEST AIRCONDITION: [object Object]
tado.0 | 2020-11-16 21:59:16.949 | info | (19488) TEST AIRCONDITION: [object Object]
tado.0 | 2020-11-16 21:59:15.514 | info | (19488) TEST AIRCONDITION: [object Object]
tado.0 | 2020-11-16 21:59:14.122 | info | (19488) TEST AIRCONDITION: [object Object]
tado.0 | 2020-11-16 21:59:12.674 | info | (19488) TEST AIRCONDITION: [object Object]
tado.0 | 2020-11-16 21:59:09.376 | info | (19488) Connected to Tado cloud, initialyzing ...
tado.0 | 2020-11-16 21:59:08.728 | info | (19488) starting. Version 0.2.2 in /opt/iobroker/node_modules/iobroker.tado, node: v14.15.0, js-controller: 3.1.6



tado.0 | 2020-11-16 21:59:20.479 | info | (19488) SPECIAL VERSION!
tado.0 | 2020-11-16 21:59:20.479 | info | (19488) Initialisation finished, connected to Tado Cloud service refreshing every : 30 seconds
tado.0 | 2020-11-16 21:59:19.674 | info | (19488) TEST AIRCONDITION: undefined
tado.0 | 2020-11-16 21:59:18.327 | info | (19488) TEST AIRCONDITION: [object Object]
tado.0 | 2020-11-16 21:59:16.949 | info | (19488) TEST AIRCONDITION: [object Object]
tado.0 | 2020-11-16 21:59:15.514 | info | (19488) TEST AIRCONDITION: [object Object]
tado.0 | 2020-11-16 21:59:14.122 | info | (19488) TEST AIRCONDITION: [object Object]
tado.0 | 2020-11-16 21:59:12.674 | info | (19488) TEST AIRCONDITION: [object Object]
tado.0 | 2020-11-16 21:59:09.376 | info | (19488) Connected to Tado cloud, initialyzing ...
tado.0 | 2020-11-16 21:59:08.728 | info | (19488) starting. Version 0.2.2 in /opt/iobroker/node_modules/iobroker.tado, node: v14.15.0, js-controller: 3.1.6
tado.0 | 2020-11-16 21:59:01.369 | info | (19473) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
tado.0 | 2020-11-16 21:59:01.368 | info | (19473) terminating
tado.0 | 2020-11-16 21:59:01.368 | info | (19473) cleaned everything up...
tado.0 | 2020-11-16 21:59:01.368 | info | (19473) Got terminate signal TERMINATE_YOURSELF
tado.0 | 2020-11-16 21:59:01.323 | error | (19473) *** Adapter deactivated, credentials missing in Adaptper Settings !!! ***
tado.0 | 2020-11-16 21:59:01.313 | info




tado.0 | 2020-11-16 21:59:20.479 | info | (19488) SPECIAL VERSION!
tado.0 | 2020-11-16 21:59:20.479 | info | (19488) Initialisation finished, connected to Tado Cloud service refreshing every : 30 seconds
tado.0 | 2020-11-16 21:59:19.674 | info | (19488) TEST AIRCONDITION: undefined
tado.0 | 2020-11-16 21:59:18.327 | info | (19488) TEST AIRCONDITION: [object Object]
tado.0 | 2020-11-16 21:59:16.949 | info | (19488) TEST AIRCONDITION: [object Object]
tado.0 | 2020-11-16 21:59:15.514 | info | (19488) TEST AIRCONDITION: [object Object]
tado.0 | 2020-11-16 21:59:14.122 | info | (19488) TEST AIRCONDITION: [object Object]
tado.0 | 2020-11-16 21:59:12.674 | info | (19488) TEST AIRCONDITION: [object Object]
tado.0 | 2020-11-16 21:59:09.376 | info | (19488) Connected to Tado cloud, initialyzing ...
tado.0 | 2020-11-16 21:59:08.728 | info | (19488) starting. Version 0.2.2 in /opt/iobroker/node_modules/iobroker.tado, node: v14.15.0, js-controller: 3.1.6
tado.0 | 2020-11-16 21:59:01.369 | info | (19473) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
tado.0 | 2020-11-16 21:59:01.368 | info | (19473) terminating
tado.0 | 2020-11-16 21:59:01.368 | info | (19473) cleaned everything up...
tado.0 | 2020-11-16 21:59:01.368 | info | (19473) Got terminate signal TERMINATE_YOURSELF
tado.0 | 2020-11-16 21:59:01.323 | error | (19473) *** Adapter deactivated, credentials missing in Adaptper Settings !!! ***
tado.0 | 2020-11-16 21:59:01.313 | info




tado.0 | 2020-11-16 21:59:20.479 | info | (19488) SPECIAL VERSION!
tado.0 | 2020-11-16 21:59:20.479 | info | (19488) Initialisation finished, connected to Tado Cloud service refreshing every : 30 seconds
tado.0 | 2020-11-16 21:59:19.674 | info | (19488) TEST AIRCONDITION: undefined
tado.0 | 2020-11-16 21:59:18.327 | info | (19488) TEST AIRCONDITION: [object Object]
tado.0 | 2020-11-16 21:59:16.949 | info | (19488) TEST AIRCONDITION: [object Object]
tado.0 | 2020-11-16 21:59:15.514 | info | (19488) TEST AIRCONDITION: [object Object]
tado.0 | 2020-11-16 21:59:14.122 | info | (19488) TEST AIRCONDITION: [object Object]
tado.0 | 2020-11-16 21:59:12.674 | info | (19488) TEST AIRCONDITION: [object Object]
tado.0 | 2020-11-16 21:59:09.376 | info | (19488) Connected to Tado cloud, initialyzing ...
tado.0 | 2020-11-16 21:59:08.728 | info | (19488) starting. Version 0.2.2 in /opt/iobroker/node_modules/iobroker.tado, node: v14.15.0, js-controller: 3.1.6
tado.0 | 2020-11-16 21:59:01.369 | info | (19473) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
tado.0 | 2020-11-16 21:59:01.368 | info | (19473) terminating
tado.0 | 2020-11-16 21:59:01.368 | info | (19473) cleaned everything up...
tado.0 | 2020-11-16 21:59:01.368 | info | (19473) Got terminate signal TERMINATE_YOURSELF
tado.0 | 2020-11-16 21:59:01.323 | error | (19473) *** Adapter deactivated, credentials missing in Adaptper Settings !!! ***
tado.0 | 2020-11-16 21:59:01.313 | info




tado.0 | 2020-11-16 21:59:20.479 | info | (19488) SPECIAL VERSION!
tado.0 | 2020-11-16 21:59:20.479 | info | (19488) Initialisation finished, connected to Tado Cloud service refreshing every : 30 seconds
tado.0 | 2020-11-16 21:59:19.674 | info | (19488) TEST AIRCONDITION: undefined
tado.0 | 2020-11-16 21:59:18.327 | info | (19488) TEST AIRCONDITION: [object Object]
tado.0 | 2020-11-16 21:59:16.949 | info | (19488) TEST AIRCONDITION: [object Object]
tado.0 | 2020-11-16 21:59:15.514 | info | (19488) TEST AIRCONDITION: [object Object]
tado.0 | 2020-11-16 21:59:14.122 | info | (19488) TEST AIRCONDITION: [object Object]
tado.0 | 2020-11-16 21:59:12.674 | info | (19488) TEST AIRCONDITION: [object Object]
tado.0 | 2020-11-16 21:59:09.376 | info | (19488) Connected to Tado cloud, initialyzing ...
tado.0 | 2020-11-16 21:59:08.728 | info | (19488) starting. Version 0.2.2 in /opt/iobroker/node_modules/iobroker.tado, node: v14.15.0, js-controller: 3.1.6
tado.0 | 2020-11-16 21:59:01.369 | info | (19473) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
tado.0 | 2020-11-16 21:59:01.368 | info | (19473) terminating
tado.0 | 2020-11-16 21:59:01.368 | info | (19473) cleaned everything up...
tado.0 | 2020-11-16 21:59:01.368 | info | (19473) Got terminate signal TERMINATE_YOURSELF
tado.0 | 2020-11-16 21:59:01.323 | error | (19473) *** Adapter deactivated, credentials missing in Adaptper Settings !!! ***
tado.0 | 2020-11-16 21:59:01.313 | info




tado.0 | 2020-11-16 21:59:20.479 | info | (19488) SPECIAL VERSION!
tado.0 | 2020-11-16 21:59:20.479 | info | (19488) Initialisation finished, connected to Tado Cloud service refreshing every : 30 seconds
tado.0 | 2020-11-16 21:59:19.674 | info | (19488) TEST AIRCONDITION: undefined
tado.0 | 2020-11-16 21:59:18.327 | info | (19488) TEST AIRCONDITION: [object Object]
tado.0 | 2020-11-16 21:59:16.949 | info | (19488) TEST AIRCONDITION: [object Object]
tado.0 | 2020-11-16 21:59:15.514 | info | (19488) TEST AIRCONDITION: [object Object]
tado.0 | 2020-11-16 21:59:14.122 | info | (19488) TEST AIRCONDITION: [object Object]
tado.0 | 2020-11-16 21:59:12.674 | info | (19488) TEST AIRCONDITION: [object Object]
tado.0 | 2020-11-16 21:59:09.376 | info | (19488) Connected to Tado cloud, initialyzing ...
tado.0 | 2020-11-16 21:59:08.728 | info | (19488) starting. Version 0.2.2 in /opt/iobroker/node_modules/iobroker.tado, node: v14.15.0, js-controller: 3.1.6
tado.0 | 2020-11-16 21:59:01.369 | info | (19473) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
tado.0 | 2020-11-16 21:59:01.368 | info | (19473) terminating
tado.0 | 2020-11-16 21:59:01.368 | info | (19473) cleaned everything up...
tado.0 | 2020-11-16 21:59:01.368 | info | (19473) Got terminate signal TERMINATE_YOURSELF
tado.0 | 2020-11-16 21:59:01.323 | error | (19473) *** Adapter deactivated, credentials missing in Adaptper Settings !!! ***
tado.0 | 2020-11-16 21:59:01.313 | info

**Comment by HGlab01** [comment]
and no longer the error?

**Comment by brasax** [comment]
I got this one:


tado.0 | 2020-11-16 22:00:05.536 | error | (19488) Disconnected from Tado cloud service ..., retry in 30 seconds !
-- | -- | -- | --
tado.0 | 2020-11-16 22:00:05.536 | error | (19488) Error in data refresh : Error: Client request error: getaddrinfo EAI_AGAIN auth.tado.com

but connection was established afterwards without issues. 

Looks like you fixed it.. :)

**Comment by HGlab01** [comment]
ok, i will remove the log entries again and then please install a last time and let it run for a coupe of minutes.
I inform you when it is ready (few minutes)

**Comment by brasax** [comment]
Great!

**Comment by HGlab01** [comment]
ok, let's try again and report if it works

**Comment by brasax** [comment]
looks good so far:

  |   |   |  
-- | -- | -- | --
tado.0 | 2020-11-16 22:09:35.980 | info | (19719) Initialisation finished, connected to Tado Cloud service refreshing every : 30 seconds
tado.0 | 2020-11-16 22:09:22.557 | info | (19719) Connected to Tado cloud, initialyzing ...
tado.0 | 2020-11-16 22:09:21.940 | info | (19719) starting. Version 0.2.2 in /opt/iobroker/node_modules/iobroker.tado, node: v14.15.0, js-controller: 3.1.6
tado.0 | 2020-11-16 22:09:18.207 | info | (19488) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
tado.0 | 2020-11-16 22:09:18.207 | info | (19488) terminating
tado.0 | 2020-11-16 22:09:18.207 | info | (19488) cleaned everything up...
tado.0 | 2020-11-16 22:09:18.207 | info | (19488) Got terminate signal TERMINATE_YOURSELF

**Comment by HGlab01** [comment]
all right! Good to hear. I will create a pull request to push it to master

**Comment by brasax** [comment]
Cool! Thanks for your effort!

**Comment by HGlab01** [comment]
PR #110 created

**Comment by DutchmanNL** [comment]
> PR #110 created

thank you, commented the PR lets continue there and close this issue.
PR will be included in next release
