### ISSUE TITLE
Fehlermeldung "Cannot read property 'percentage' of undefined"

### ISSUE THREAD

**Issue by t6a** [iobroker-community-adapters/ioBroker.tado#9]
Volle Fehlermeldung: 
"Issue in Get all roomsTypeError: Cannot read property 'percentage' of undefined"

Die Meldung kommt nur bei dem Tado System welches u.a. eine Gastherme mit Warmwassererzeugung steuert. Mein anderes Tado System welches nur aus Heizkörperthermostaten besteht bekommt keine Fehlermeldung.

<img width="1173" alt="Screenshot 2019-11-29 at 00 17 23" src="https://user-images.githubusercontent.com/16940364/69884648-9da10480-12d9-11ea-9224-41a0612fcb7e.png">

**Comment by DutchmanNL** [comment]
poste mal bitte den Inhalt von_info.JSON_response.Stage_02_HomeData

**Comment by senger1985** [comment]
Bitte die sensiblen Daten, xen.

Beispiel:
{"id":143236,"name":"Home","dateTimeZone":"Europe/Berlin","dateCreated":"2017-12-02T06:39:55.120Z","temperatureUnit":"CELSIUS","installationCompleted":true,"partner":null,"simpleSmartScheduleEnabled":true,"awayRadiusInMeters":237.24,"skills":["AUTO_ASSIST"],"christmasModeEnabled":true,"showAutoAssistReminders":true,"contactDetails":{"name":"Michael Senger","email":"xyz@xyz.com","phone":"+123456789"},"address":{"addressLine1":"Geht euch nichts an","addressLine2":null,"zipCode":"12345","city":"Buxtehude","state":null,"country":"DEU"},"geolocation":{"latitude":xx.xxx,"longitude":xx.xxx},"consentGrantSkippable":true}

**Comment by t6a** [comment]
Ok, wie ist der Pfad zur Datei?

**Comment by t6a** [comment]
{"id":21248,"name":"Husemannstrasse","dateTimeZone":"Europe/Berlin","dateCreated":"2015-07-03T10:03:55.081Z","temperatureUnit":"CELSIUS","installationCompleted":true,"partner":null,"simpleSmartScheduleEnabled":true,"awayRadiusInMeters":400,"skills":["AUTO_ASSIST"],"christmasModeEnabled":true,"showAutoAssistReminders":true,"contactDetails":{"name":"Alexander XXXXXX","email":"XXXXXX@gmail.com","phone":"+49XXXXXX"},"address":{"addressLine1":"Husemannstraße XXXXXX","addressLine2":null,"zipCode":"XXXXXX","city":"XXXXXX","state":null,"country":"DEU"},"geolocation":{"latitude":XXXXXX,"longitude":XXXXXX},"consentGrantSkippable":true}

**Comment by DutchmanNL** [comment]
danke, bitte auch die JSON von Stage_08_ZonesData

**Comment by t6a** [comment]
[{"id":2,"name":"H10 balcony room","type":"HEATING","dateCreated":"2018-08-09T12:29:22.309Z","deviceTypes":["RU01","VA02"],"devices":[{"deviceType":"RU01","serialNo":"RU1410FT01052738356224","shortSerialNo":"RU2738356224","currentFwVersion":"54.16","connectionState":{"value":true,"timestamp":"2019-12-04T10:38:26.530Z"},"characteristics":{"capabilities":["INSIDE_TEMPERATURE_MEASUREMENT","IDENTIFY"]},"batteryState":"NORMAL","duties":["ZONE_UI","CIRCUIT_DRIVER","ZONE_LEADER"]},{"deviceType":"VA02","serialNo":"VA2266369792","shortSerialNo":"VA2266369792","currentFwVersion":"62.3","connectionState":{"value":true,"timestamp":"2019-12-04T10:32:33.603Z"},"characteristics":{"capabilities":["INSIDE_TEMPERATURE_MEASUREMENT","IDENTIFY"]},"mountingState":{"value":"CALIBRATED","timestamp":"2019-11-23T19:06:45.172Z"},"batteryState":"NORMAL","duties":["ZONE_UI","ZONE_DRIVER"]}],"reportAvailable":false,"supportsDazzle":true,"dazzleEnabled":true,"dazzleMode":{"supported":true,"enabled":true},"openWindowDetection":{"supported":true,"enabled":true,"timeoutInSeconds":3600}},{"id":3,"name":"H10 small room","type":"HEATING","dateCreated":"2018-12-25T12:31:15.295Z","deviceTypes":["VA02"],"devices":[{"deviceType":"VA02","serialNo":"VA3797814528","shortSerialNo":"VA3797814528","currentFwVersion":"62.3","connectionState":{"value":true,"timestamp":"2019-12-04T10:41:19.270Z"},"characteristics":{"capabilities":["INSIDE_TEMPERATURE_MEASUREMENT","IDENTIFY"]},"mountingState":{"value":"CALIBRATED","timestamp":"2019-11-23T18:49:12.102Z"},"batteryState":"NORMAL","duties":["ZONE_UI","ZONE_DRIVER","ZONE_LEADER"]}],"reportAvailable":false,"supportsDazzle":true,"dazzleEnabled":true,"dazzleMode":{"supported":true,"enabled":true},"openWindowDetection":{"supported":true,"enabled":true,"timeoutInSeconds":3600}},{"id":4,"name":"H10 high bed room","type":"HEATING","dateCreated":"2018-12-25T12:40:00.068Z","deviceTypes":["VA02"],"devices":[{"deviceType":"VA02","serialNo":"VA1307315200","shortSerialNo":"VA1307315200","currentFwVersion":"62.3","connectionState":{"value":true,"timestamp":"2019-12-04T10:45:50.069Z"},"characteristics":{"capabilities":["INSIDE_TEMPERATURE_MEASUREMENT","IDENTIFY"]},"mountingState":{"value":"CALIBRATED","timestamp":"2019-11-24T16:22:43.165Z"},"batteryState":"NORMAL","duties":["ZONE_UI","ZONE_DRIVER","ZONE_LEADER"]}],"reportAvailable":false,"supportsDazzle":true,"dazzleEnabled":true,"dazzleMode":{"supported":true,"enabled":true},"openWindowDetection":{"supported":true,"enabled":true,"timeoutInSeconds":3600}},{"id":5,"name":"H10 kitchen","type":"HEATING","dateCreated":"2018-12-25T13:01:22.839Z","deviceTypes":["VA02"],"devices":[{"deviceType":"VA02","serialNo":"VA1376849664","shortSerialNo":"VA1376849664","currentFwVersion":"62.3","connectionState":{"value":true,"timestamp":"2019-12-04T10:40:02.526Z"},"characteristics":{"capabilities":["INSIDE_TEMPERATURE_MEASUREMENT","IDENTIFY"]},"mountingState":{"value":"CALIBRATED","timestamp":"2019-11-23T18:36:06.638Z"},"batteryState":"NORMAL","duties":["ZONE_UI","ZONE_DRIVER","ZONE_LEADER"]}],"reportAvailable":false,"supportsDazzle":true,"dazzleEnabled":true,"dazzleMode":{"supported":true,"enabled":true},"openWindowDetection":{"supported":true,"enabled":true,"timeoutInSeconds":900}},{"id":6,"name":"H10  bathroom","type":"HEATING","dateCreated":"2018-12-25T13:09:50.253Z","deviceTypes":["VA02"],"devices":[{"deviceType":"VA02","serialNo":"VA1913982720","shortSerialNo":"VA1913982720","currentFwVersion":"54.7","connectionState":{"value":true,"timestamp":"2019-12-04T10:48:21.049Z"},"characteristics":{"capabilities":["INSIDE_TEMPERATURE_MEASUREMENT","IDENTIFY"]},"mountingState":{"value":"CALIBRATED","timestamp":"2019-11-23T18:43:35.511Z"},"batteryState":"NORMAL","duties":["ZONE_UI","ZONE_DRIVER","ZONE_LEADER"]}],"reportAvailable":false,"supportsDazzle":true,"dazzleEnabled":true,"dazzleMode":{"supported":true,"enabled":true},"openWindowDetection":{"supported":true,"enabled":true,"timeoutInSeconds":1800}},{"id":0,"name":"H10 Warmwater","type":"HOT_WATER","dateCreated":"2018-11-30T11:32:56.483Z","deviceTypes":["RU01"],"devices":[{"deviceType":"RU01","serialNo":"RU1410FT01052738356224","shortSerialNo":"RU2738356224","currentFwVersion":"54.16","connectionState":{"value":true,"timestamp":"2019-12-04T10:38:26.530Z"},"characteristics":{"capabilities":["INSIDE_TEMPERATURE_MEASUREMENT","IDENTIFY"]},"batteryState":"NORMAL","duties":["ZONE_UI","ZONE_DRIVER","ZONE_LEADER"]}],"reportAvailable":false,"supportsDazzle":false,"dazzleEnabled":false,"dazzleMode":{"supported":false},"openWindowDetection":{"supported":false}}]

**Comment by DutchmanNL** [comment]
> Danke für den Support!
> Wann gibts es denn die stable version? Denke die meisten User haben die Adapter Source bei default belassen und sehen den Adapter gar nicht...

er ist fast. stable also vor weinachten kommt er raus, nur bevor hunderte ihn benutzen erstmal beta und im kleine Kreis Produktions faehig machen ;)

danke ich schau mir die JSON mal weiter an und komme drauf zurück

**Comment by DutchmanNL** [comment]
wurde bei dir fuer alle räume Datenpunkte erstellt oder fehlt da einer ?

**Comment by DutchmanNL** [comment]
und brauchte bitte auch noch die Stage_09_ZoneStates_data_

**Comment by t6a** [comment]
> wurde bei dir fuer alle räume Datenpunkte erstellt oder fehlt da einer ?

Alle Räume + Warmwasserversorgung sind gelistet.

Hier die JSON von Stage_09_ZoneStates_data_0 

{"tadoMode":"HOME","geolocationOverride":true,"geolocationOverrideDisableTime":"2019-12-07T12:00:00Z","preparation":null,"setting":{"type":"HOT_WATER","power":"ON","temperature":{"celsius":46,"fahrenheit":114.8}},"overlayType":null,"overlay":null,"openWindow":null,"nextScheduleChange":{"start":"2019-12-07T12:00:00Z","setting":{"type":"HOT_WATER","power":"OFF","temperature":null}},"nextTimeBlock":{"start":"2019-12-07T12:00:00.000Z"},"link":{"state":"ONLINE"},"activityDataPoints":{},"sensorDataPoints":{}}

**Comment by DutchmanNL** [comment]
auch da kein percentage wo zum T kommt das her grrrr

mal ne dumme frage : wuerdes du mir erlauben mal deine credentials bei mir im adapter ein zu geben (also mach mal n simples Passwort draus). glaube sonst zieht sich das hier noch Monate hin :)

**Comment by t6a** [comment]
okay schicke ich dir via telegram

**Comment by Uwe1984** [comment]
Hallo DutchmanNL, im Forum habe ich dir ja von dem gleichen Error berichtet. Auch ich habe eine Gastherme mit Tado System... Gruß K_o_bold ;-). 
Ich wollte dir schon ein Issue schreiben, aber läuft ja schon was. Wenn ich unterstützen kann, gerne melden.

**Comment by t6a** [comment]
Meine Telegram messages kommen nicht bei Dir an...?

**Comment by DutchmanNL** [comment]
> Meine Telegram messages kommen nicht bei Dir an...?

da kommt nix rein bei mir, haste den richtige Benutzer im telegram heisse ich nicht Dutchman :)

**Comment by t6a** [comment]
Wir hatten ja schon geschrieben.

**Comment by DutchmanNL** [comment]
> Wir hatten ja schon geschrieben.

jetzt bin ich verwirrt ping mich nochmals an bitte

**Comment by t6a** [comment]
@RaffiDuck

**Comment by t6a** [comment]
Sonst schreib mir nochmal @Asbeck

**Comment by DutchmanNL** [comment]
fixed in 0.1.4, please try https://github.com/iobroker-community-adapters/ioBroker.tado/commit/80147acea9b6de23cecd27c1b3529e2ee982f799
