### ISSUE TITLE
Send this info to developer !!! { Unhandable information found in DoHome : "autoAssistFreeTrialEnabled" with value : false

### ISSUE THREAD

**Issue by HGlab01** [iobroker-community-adapters/ioBroker.tado#95]
**Describe the bug**  
Error "Send this info to developer !!! { Unhandable information found in DoHome : "autoAssistFreeTrialEnabled" with value : false" appears by every polling since today in the log due to a new attribute is provided by the interface.

**To Reproduce**  
Run v0.2.1 and check the kog.

I will create a PR today in the evening.

**Comment by HGlab01** [comment]
PR #97 created

**Comment by janhp** [comment]
same here! please fix

**Comment by cyrildegen** [comment]
same here! Every 30-40sec

**Comment by HGlab01** [comment]
If you like you can install the fork on your own risk at
https://github.com/HGlab01/ioBroker.tado
until it is fixed in this repository. For me and others it worked smoothly.

How: https://github.com/iobroker-community-adapters/ioBroker.tado/issues/62#issuecomment-716326327

**Comment by Grothesk242** [comment]
Forked version works. Please pull upstream.

**Comment by DutchmanNL** [comment]
> If you like you can install the fork on your own risk at
> https://github.com/HGlab01/ioBroker.tado
> until it is fixed in this repository. For me and others it worked smoothly.
> 
> How: [#62 (comment)](https://github.com/iobroker-community-adapters/ioBroker.tado/issues/62#issuecomment-716326327)

You Rock ! Will look at the pr this Weekend

**Comment by HGlab01** [comment]
> You Rock ! Will look at the pr this Weekend

This was the easy part of my three PRs  ;-)

**Comment by cortanaDE** [comment]
lol
@HGlab01 
That's not true. The beads of sweat ran off your forehead.
Or was it just tears?   ;-D

**Comment by HGlab01** [comment]
Men do not cry  ;-)

**Comment by DutchmanNL** [comment]
https://github.com/iobroker-community-adapters/ioBroker.tado/commit/f32410b79c143534a081a3b1733533fc7537b79d

**Comment by OXERY** [comment]
Same "problem" here, adapter works besides the Log Spam.
Thanks for the great work!
